README.md
Update link in README from https://github.com/GaloyMoney/galoy-infra to https://github.com/GaloyMoney/galoy.
=> Update README link with correct galoy link

app/i18n/es.json
This will remove the line break in the 'send screen' when using ES translation
=> fix: translation

app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx, ios/Podfile.lock
PR relates to [issue 13](https://github.com/GaloyMoney/galoy-mobile/issues/13).
Most of the changes are prettier, with the only relevant change being on line 419.
The value used in QR codes have been converted to uppercase to simplify the QR image. I have opted to not uppercase the value that is displayed below the QR code for viewability purposes, but I can change this too if thought to be neccessary.
=> value of qrcode to uppercase to simplify qr code image

app/components/input-payment/input-payment.tsx, app/utils/currencyConversion.ts
Implements enhancement proposed in #100.
~As far as I can tell it is not possible to avoid the flickering issue when adding values on the right hand side of the decimal point without overlaying a Text field that covers/masks the input field thus fixing the cursor to the end and sacrificing the ability to do selections and interact with the input field in ways that one may expect. Let me know if you think we should go with the masked approach, then I'll revise this PR. @nicolasburtey @jrbuhl93~ **edit:** New approach below
~More details about this issue here: https://github.com/CaioQuirinoMedeiros/react-native-currency-input#fakecurrencyinput~ 
<details>
<summary>Prior approach demo</summary>
https://user-images.githubusercontent.com/959142/126685362-42163139-fe99-4b14-bf3a-4f9af28d27a4.mp4 …
=> feat: amounts should be set in cts, not dollar

app/components/price-graph/price-graph.tsx
Despite having the translations the price graph titles weren't being translated before this PR.
=> Render mapping in component so translate works

app/utils/parsing.ts
I'm not sure if this fixes #114  because I don't know an easy way to generate a valid lightning address with pico btc yet (my Phoenix wallet used nano), but it seems likely that it will.
=> Possible fix for a pico amount of btc from Phoenix lightning invoice

app/graphql/__generated__/LastClipboardPayment.ts, app/graphql/schema.graphql, app/utils/clipboard.ts
Fixes a bug when reading `lastClipboardPayment` from apollo cache when the value is null.
=> Check for null when reading clipboard cache

app/graphql/query.ts, app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx
Fixes #141. I am not sure exactly how useQuery and useLazyQuery work, but it seems if you leave the component before they complete, the data retrieved from them will not update in the cache. By separating the updateWallet query from the component we ensure that the cache is updated when the query completes.
=> fetch wallet updates separate from useLazyQuery

__tests__/screens/__snapshots__/send-bitcoin-screen.spec.tsx.snap, app/components/input-payment/input-payment.tsx, app/navigation/root-navigator.tsx, app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx, app/utils/currencyConversion.ts
Fixes issue #151. But there is a catch. This PR causes the text to center differently betweens `sats` and `$`.
https://user-images.githubusercontent.com/35902932/129268102-889b30b7-b4b1-40ab-b597-72761720f846.mp4
This is because the margins to avoid the unit symbols are different.
If the change of text positioning is unacceptable we can either:
1. Leave the margins the same between currencies. This requires using the strictest margins for all currencies. This leaves unused white space (`$` space for an amount in sats and `sats` space for an amount in dollars). This is what the current version of the app does.
2. Dynamically alter the margins as more text is added so that the amount starts in the center, but can fill in the blank space as more digits are added. The downside is that this is …
=> Cap amount digits and custom margins for currencies

app/graphql/query.ts, app/screens/phone-auth-screen/phone-auth.tsx
Mostly fixes #97. 
This doesn't change the logic for what to do if a user reaches the home screen without the main query data. It also doesn't force the main query data to load before reaching the home screen. But similarly to #142 it takes the networking call in phone-auth out of the component, so that the response data is cached if the request completes after leaving the phone-auth component.
This will make the problem much less noticeable, so it might not be worth the added complexity to do more.
=> Query main outside of component

app/screens/receive-bitcoin-screen/ReceiveBitcoinScreenTypes.d.ts, app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx
Fixes #155
Added an extra param to be able to get the full uri with (default) or without the `bitcoin:` prefix.
=> fix: Add param to get full uri without prefix

app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx
Increased the error correction level from low to medium when generating a qr code for onchain in the receive screen. Lightning remains at low. If onchain scanning remains an issue, there are two more levels of redundancy: quartile then high.
=> Increase bitcoin address qr code ECL

README.md, app/components/balance-header/balance-header.tsx, app/graphql/client-only-query.ts, app/i18n/en.json, app/navigation/stack-param-lists.ts, app/screens/move-money-screen/move-money-screen.tsx, app/screens/price-screen/price-screen.tsx, app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx, app/screens/settings-screen/security-screen.tsx, app/screens/settings-screen/settings-screen.tsx, ios/Podfile.lock, package.json, yarn.lock
Had some issues with my IDE will re-basing my branch so I closed this original [Pull Request](https://github.com/GaloyMoney/galoy-mobile/pull/144)
In summary- These changes implement the security feature to hide the user's balance on the home and send screens, replacing the balance with an eye icon that can be toggled between hidden and shown if touched.
=> Hide balance security setting

__tests__/addresses.spec.ts, android/build.gradle, app/utils/parsing.ts
p2pkh and p2sh are case sensitive, so we should only lowercase lightning invoices and bech 32 paths.
=> Don't lowercase addresses that might be p2pkh or p2sh

app/constants/support.ts, app/i18n/en.json, app/i18n/es.json, app/screens/settings-screen/settings-screen.tsx, app/utils/toast.ts
Added the settings menu item to advertise sharing of user's tip links. Copies the tip link to their clipboard and uses Toast to display that they copied their link so they can share. This PR is an attempt to satisfy [Issue #182](https://github.com/GaloyMoney/galoy-mobile/issues/182)
=> Feature advertise copy tip link

__tests__/username-validation.spec.ts, app/i18n/en.json, app/i18n/es.json, app/screens/settings-screen/username-screen.tsx, app/utils/validation.ts
Fixes https://github.com/GaloyMoney/galoy-mobile/issues/196
Worth noting someone might need a proper Spanish translation as this was just a quick Google Translate, thanks!
**Changes**
Now shows an error message when trying to create a username beginning with 'bc1', '1', or '3'.
=> Add restriction on username start characters

app/screens/transaction-detail-screen/transaction-detail-screen.tsx
This was overlooked when refactoring currencyType.
=> Display sats in transaction details

README.md
New link + info about the tab to follow.
Because using "Expo CLI Quickstart" will lead to many issues.
=> Install react native in README.md

app/hooks/use-wallet-balance.ts, app/hooks/user-hooks.ts, app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx, yarn.lock
There was a race condition whereby the send bitcoin confirmation screen would momentarily flash up an error saying that the user did not have sufficient balance to process the transaction.  I have added a workaround for now to include a loading indicator for 2 of the queries we are using.  I think we need to refactor this code into a better design as right now it's hard to work out the relationships which components have as our hooks are relying on each other.
=> Fixed race condition for user balance

ios/GaloyApp/Info.plist
The iOS build is failing with an error regarding the status of `ITSAppUsesNonExemptEncryption` key value.  I had added this because otherwise it asks us in the App Store connect to define whether the app uses encryption.  There is some conflicting information online as to whether our app should be marked as using encryption or not.  For now I'm marking it as not using it.
=> Setting encryption use to false

README.md
The storybook config in the README directed devs to edit SHOW_STORYBOOK in app/app.tsx when it is actually in app/index.js﻿
=> Edited README for storybook config in app/index.js, not app/app.tsx

app/navigation/root-navigator.tsx
added headerBackTitle to Navigator's `screenOptions` prop to apply to all child screens
=> Fix missing 'back' translation

app/components/transaction-item/transaction-item.tsx
User can click on amount to toggle visibility for that specific tx.
Resolves #319
=> add masking to transaction items if balances are hidden in user settings

app/screens/map-screen/map-screen.tsx, app/screens/transaction-screen/transaction-screen.tsx
The title was missing from the map markers and the "switch direction" icon was missing from the transactions list screen.
=> Fix missing icons/fonts

__tests__/screens/__snapshots__/send-bitcoin-confirmation-screen.spec.tsx.snap, __tests__/screens/send-bitcoin-confirmation-screen.spec.tsx, app/components/balance-header/balance-header.tsx, app/graphql/client-only-query.ts, app/graphql/init.ts, app/hooks/use-wallet-balance.ts, app/navigation/root-navigator.tsx, app/screens/contacts-screen/contacts-detail.tsx, app/screens/contacts-screen/contacts.tsx, app/screens/earns-screen/earns-section.tsx, app/screens/receive-bitcoin-screen/qr-view.tsx, app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx, app/screens/settings-screen/language-screen.tsx, app/screens/settings-screen/username-screen.tsx
Include refactoring of BalanceHeader to not invoke its hooks
while the main query is loading, and a few other minor fixes
This commit also fixes the Balance 0 problem after navigating to
contacts screen. This was an Apollo cache missing field problem
because the contacts screen was querying the me field without and id
=> fix: use a reactive-var to reset cache after mutations

app/graphql/graphql.types.d.ts, app/screens/transaction-detail-screen/transaction-detail-screen.tsx
Salim noticed that lightning payment hashes were missing from the transaction details screen.  This was removed by mistake because we were looking for it in the wrong place in the server response.  We should be getting the hash from the `initiationVia` field.
=> Fix missing hash in lightning transactions

.eslintrc.json, app/app.tsx, app/components/global-error/global-error.tsx, app/i18n/en.json, app/i18n/es.json, app/screens/error-screen/error-screen.tsx, app/screens/error-screen/index.ts, jest.config.js, package.json, yarn.lock
Me and @samerbuna paired up and found out the library I was trying to use just wasn't compatible with react-native.  @samerbuna found this library which has a very similar API but works for react-native.  This should mean that users are no longer presented with the _white screen of death_.  Example of error screen shown below.
=> feat: Add error boundary

android/settings.gradle, app/utils/network.ts, ios/Podfile, ios/Podfile.lock, jest.config.js
This change includes a change to make the default network testnet in dev builds.  This is to avoid the bug that @samerbuna mentioned where the app fails to load in dev mode if you don't have the backend running.  It also removes the `react-native-exception-handler` library from some files as it is referencing a library which is no longer installed.
=> fix: Change default dev network

app/hooks/use-main-query.ts, app/screens/error-screen/error-screen.tsx
After a lot of debugging I found out that we have a few issues with crashlytics.
1. Crashlytics batches up errors on android and only reports the batch when the app restarts.
2. For the errors in the `useMainQuery` hook we are throwing strings instead of javascript errors.  Crashlytics has some validation on objects passed to the `recordError` method to make sure it's a proper javascript error.
This PR fixes point 2.
=> fix: Fix crashlytics error reporting

app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx
Our beta testers identified an issue with the lnurl-pay implementation. The app was not converting the USD amount to BTC properly when hitting the lnurl-pay callback URL. This resulted in an invoice of the incorrect amount being created on the back-end.
=> Resolve USD to BTC issue with lnurl-pay

__tests__/screens/global-error.spec.tsx, app/components/global-error/global-error.tsx, app/i18n/en.json, app/i18n/es.json
This PR has the mobile app respond to 401 Unauthorized responses from the GraphQL API by notifying the user and  This is a small change that fixes existing code that wasn't being triggered as expected.
=> fix: Handle 401 Unauthorized Responses from GraphQL

app/screens/transaction-detail-screen/transaction-detail-screen.tsx
Right now this link is included in every row in the transactions details screen.  We only want to include it on the on chain payment rows.
=> fix: Fix block explorer link

app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx
After doing some research on the topic, the consensus seems to be that you should tweak the debounce time until you get the right balance of app feedback to the user in a timely manner and reducing server load. I went with 500ms for now. 
I tried to simulate entering a username from a list of examples that required me to stop briefly to look as I typed and 1500ms triggered the function call the fewest times while not taking an unreasonable time to provide validation feedback.
resolve: #364
=> perf: increase debounce time

__tests__/username-validation.spec.ts, app/i18n/en.json, app/i18n/es.json, app/screens/settings-screen/username-screen.tsx, app/utils/validation.ts
Resolves #365 
- Adds "lnbc1" to the `hasNoRestictedStartCharacters` function to reduce calls to the server. 
- Adds some clarity to the forbiddenStart message letting the user know the username cannot be a bitcoin address or lightning invoice
- Adds test for "lnbc1" 
*Note - I did my best to translate the forbidden start error message which may benefit from being proofed by a native Spanish speaker. The added language may not be even be necessary and can be removed also.
=> perf: Improve validation for usernameAvailable

app/i18n/en.json, app/i18n/es.json, app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx, app/utils/parsing.ts
Addresses issue #316 
Send Bitcoin screen was able to handle lnurl from scanned QR code but was not able to handle user pasting lnurl directly.
- added ability to paste lnurl from send bitcoin screen 
- added clipboard icon to bottom of QR code, if user has copied it to clipboard and taps the clipboard it will paste and transition to send bitcoin screen to confirm, similar to Wallet of Satoshi and Strik
https://user-images.githubusercontent.com/17483038/151304524-8c7487ab-3a25-4be0-8e32-1bac5f83c890.mov
=> refactor: Enable paste lnurl

app/constants/support.ts, app/screens/settings-screen/lnurl-screen.tsx, app/screens/settings-screen/settings-screen.tsx
This PR changes the new LNURL screen to use the `LN_PAGE_DOMAIN` constant instead of the hardcoded string of `ln.bitcoinbeach.com`. This makes it easier for other instances of Galoy to incorporate this change into their repo.
=> Fix: Change `LN_PAGE_DOMAIN` to `GALOY_PAY_DOMAIN`, Use `GALOY_PAY_DOMAIN` constant in LNURL screen.

app/screens/contacts-screen/contacts-detail.tsx
As reported in issue #355 the contact screen was not displaying properly on smaller devices. I have reduced the padding in the header and the user icon / contact text size so that it gives more room for the bottom transaction section on smaller devices.
=> fix: Make contact header smaller so fits better on smaller screens

__tests__/screens/__snapshots__/phone-auth.spec.tsx.snap, app/i18n/en.json, app/i18n/es.json, app/screens/phone-auth-screen/phone-auth.tsx
As requested in issue #390 I have added a Continue button to the phone auth screen. Now users can either use the submit button on the keyboard or they can dismiss the keyboard and hit the Continue button when they are ready. I can adjust the styling if you had something different in mind for the design.
Cheers!
Screenshot:
=> feat: Add continue button to phone auth screen

app/screens/phone-auth-screen/phone-auth.tsx
We had some alerts recently due to duplicate key errors in mongodb.  We traced it back to duplicate login calls from the mobile app.  We didn't have protection preventing the user from using the enter key to submit the form while the form was loading.
=> fix: fix userLogin action while loading

.circleci/config.yml
Adds additional CI Step to upload release APK/IPAs to mobile releases.
=> feat: upload apk and ipa to github release

app/components/price-graph/price-graph.tsx
Update delta calculation in price graph. Please notice that we dont need to convert prices to do the calculation
=> fix: update delta calc in price graph

app/components/balance-header/balance-header.tsx, app/screens/move-money-screen/move-money-screen.tsx
- prevent buttons on homescreen from moving during a refresh
=> fix: keep header still during reload

app/components/balance-header/balance-header.tsx, app/components/wallet-overview/wallet-overview.story.tsx, app/components/wallet-overview/wallet-overview.tsx, app/screens/move-money-screen/move-money-screen.tsx
- Removes use of useWalletBalance from the component level and returns it to the screen level to prevent inconsistent balances across components
- addresses issue #562
=> fix: inconsistent wallet balances

app/screens/transfer-screen/transfer-confirmation-screen.tsx
The amount submitted for `intraLedgerUsdPaymentSend` mutation was a float when the amount included cents - this was causing errors on the backend when attempting to transfer between usd -> btc.
=> fix: Fixed transfer screen usd -> btc bug

app/navigation/stack-param-lists.ts, app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- ensure destination is properly passed across screens
- ensure usd + btc amounts are present for calculating fees. Currently it is trying to calculate the fee using a paymentAmount that hasn't been converted yet to the proper currency and is resulting in NaN. This is fixed by passing in both usd and btc values into the "send-bitcoin-confirmation" screen
=> fix: send bitcoin flow

package.json, yarn.lock
We saw some behaviour differences when trying to parse the pay urls on android/ios.  This PR upgrades the client which has a [fix for the issue](https://github.com/GaloyMoney/galoy-client/pull/67).
=> fix: Fixed scan pay URL on android

app/components/transaction-date/transaction-date.tsx
The client returns the locale as `en-US` when English is the preferred user language.  This causes errors in moment which completely crashes the app as can be seen here https://stackoverflow.com/a/69605154.  I don't think setting the locale is actually necessary because the format operation we are using is aware of timezones.
=> fix: Fixed crash when english is selected language

app/app.tsx, app/graphql/cache.ts
Momentjs isn't currently displaying dates correctly for French Canadian or Brazilian Portuguese translations.  We need to import the translation files from momentjs library.
=> fix: Added momentjs translation files for locales

app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- fixes issue of whenever the amount exceeded the current balance the page entered an infinite loop of setting an error message
=> fix: prevent infinite re-render on send confirmation

app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
lnurl payments were broken since the refactor since the `useFee` hook was being passed a null value.  The fix was to ensure that lnurl invoices are being treated as fixed amount invoices.
=> fix: Fixed lnurl payments issue

app/components/modal-clipboard/modal-clipboard.tsx, app/screens/receive-bitcoin-screen/receive-btc.tsx, app/screens/receive-bitcoin-screen/receive-usd.tsx, app/screens/settings-screen/lnurl-screen.tsx, app/screens/settings-screen/settings-screen.tsx, app/utils/clipboard.ts
Currently if a user creates an invoice, leaves the app, and then returns, the clipboard modal will ask if they want to open the invoice. This PR prevents the clipboard modal from being triggered for invoices created by the application.
=> fix: dont trigger clipboard on own invoice

app/app.tsx, package.json, yarn.lock
The `typesafe-i18n` library makes use of [Intl.PluralRules](https://github.com/ivanhofer/typesafe-i18n/blob/3035050922a33d87c817114b0ee3789cd174b5bd/packages/runtime/src/util.object.mts#L25) which currently [isn't supported by hermes](https://hermesengine.dev/docs/intl/#not-yet-supported) (although weirdly seems to be supported by the ios version of hermes).  I've introduced a [polyfill](https://github.com/eemeli/intl-pluralrules) until this namespace is supported in hermes.
=> fix: Fixed typed translations on android

app/app.tsx, app/utils/locale-detector.ts
I tested the translation changes on a device using browserstack and changed the locale to Spanish at the OS level - this should have made the default language Spanish on a device which wasn't logged in (and so didn't have a preferred language set using the API), but it defaulted to English instead.  I realised that I forgot to use the `customLocaleDetector` which I wrote when initially setting the locale.  I think this should fix it.
=> fix: Fixed default language selection

app/app.tsx
The default for this value is [infinity](https://github.com/apollographql/subscriptions-transport-ws/blob/323e3af83f13512d320125ae2a00be25433fb9d0/src/client.ts#L114).  I'm hoping this will improve the rate limiting of websocket connections we are seeing in the tracing.
=> fix: Added max reconnection on websocket

package.json, yarn.lock
This pulls in an upstream fix that allows for case-sensitive lightning addresses
=> chore: bump galoy-client

app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
- When navigating from scan screen to send-bitcoin-destination the scan screen keeps operating in the background and causes several navigation actions to occur, this causes quirks in the send-bitcoin-destination-screen. This PR uses `navigation.replace` and `isFocused` to ensure that the scan screen does not operate in the background
=> fix: screen navigation quirk

app/app.tsx, app/hooks/use-logout.ts, app/screens/debug-screen/debug-screen.tsx
- remove async method used in galoy config changes that was preventing batching of state updates
=> fix: prevent extra renders on client change

.circleci/config.yml, docs/e2e-testing.md, e2e/02-login-flow.e2e.spec.ts, e2e/config/wdio.conf.js
@nicolasburtey 
This PR should fix the android apk path and use the universal apk or you can configure the path with the env var `TEST_APK_PATH`. It also fixes one of the flakes on ios when logging in
=> fix: update android universal apk path for e2e test

ci/pipeline.yml
the idea is to always have main available on testflight on a daily basis to the team internally. we should all be onboarded into it so we can detect early regression that the tests would have not catched.
=> chore: build a daily version to testflight internal

.circleci/config.yml
if we don't do test also for iOS, what will most likely happen is that while iOS will likely be working just fine, the e2e tests will be the one to break, before there often need some custom attributes to be set for webdriverio for the tests to pass successfully on iOS.
this PR is a good example of the issue https://github.com/GaloyMoney/galoy-mobile/pull/821
while tests were passing in the PR, they didn't pass on main.
=> chore: do test_ios on every build, including in PR

docs/e2e-testing.md, e2e/config/browserstack.conf.js, e2e/config/wdio.conf.js, package.json, yarn.lock
browserstack seems to still run on v1 but also seem to be running fine for now.
maybe we can update on browserstack at a later date?
=> chore: upgrade to appium v2 locally

e2e/04-username-payments-flow.e2e.spec.ts
The test props ID we were using to grab the elements in move money screen was changed. It was updated in `lightning-invoice-payment` test but not on `username-payment` test because the two e2e PR's came in separately. This PR fixes that.
Also, I added a conditional check when making username payments to check if the username is already a contact or not.
=> fix: check if username is a contact before payment

app/graphql/generated.gql, app/graphql/generated.ts, app/screens/contacts-screen/contacts.tsx, app/screens/conversion-flow/conversion-confirmation-screen.tsx, app/screens/galoy-address-screen/galoy-address-screen.tsx, app/screens/galoy-address-screen/merchants-dropdown.tsx, app/screens/galoy-address-screen/set-default-wallet.tsx, app/screens/map-screen/map-screen.tsx, app/screens/receive-bitcoin-screen/receive-bitcoin.tsx, app/screens/receive-bitcoin-screen/receive-btc.tsx, app/screens/receive-bitcoin-screen/receive-usd.tsx, app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx, app/screens/settings-screen/account-screen.tsx, app/screens/settings-screen/language-screen.tsx, app/screens/settings-screen/settings-screen.tsx, app/screens/settings-screen/transaction-limits-screen.tsx, app/store/localization-context.tsx, e2e/utils/graphql.ts
this should help with caching
I don't know what is the effect of object which don't have an id, like:
```
globals {
network
}
me {
...
}
```
does the globals request force a network request because `globals.networks` is not cache properly because there is no `globals.id` ? I will dive in this later.
=> chore: include ids in queries

.gitignore, android/app/src/main/java/com/galoyapp/MainApplication.java
I noticed sometimes the android build will connect to metro during e2e tests in browserstack - this is probably related to the change I made recently as setup work to enable camera testing.  It could be that it's trying to connect to metro dev services in the android native code so I've disabled that when building in a CI env.
=> chore: Fix android build

app/graphql/client.tsx
there is no need to subscribe to the price sub when a client is not auth. no action requires it.
this will save ressources server side and limiit bandwiith on the phone
=> chore: remove sub for unauth client

app/screens/settings-screen/settings-screen.tsx
The server responds with an [empty string](https://github.com/GaloyMoney/galoy/blob/6bbbbb46ed3e196ab362c7c875207dbff7059ba2/src/graphql/types/scalar/language.ts#L30) if the language is set as default and the code doesn't deal with this at the moment.  I was seeing the `FIXME: error missing language` message in the settings page when my language was set as default.
=> fix: Fixed language parsing issue on settings page

app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx, e2e/04-username-payments-flow.e2e.spec.ts
BTC wallet sat balance was showing as `NaN` on the send flow.  I also added a new test to look out for this in future.
=> fix: Fixed issue with btc wallet balance

app/app.tsx, app/components/contact-modal/contact-modal.tsx, app/screens/settings-screen/settings-row.tsx, app/screens/settings-screen/settings-screen.story.tsx, app/screens/settings-screen/settings-screen.tsx, package.json, storybook/storybook-registry.ts, storybook/storybook.tsx, storybook/views/story-screen.tsx, storybook/views/story.tsx, yarn.lock
also:
- remove `mock-apollo-client`. a better version is already included with apollo
- make settings screen works back with storybook
- add i18n wrapper for storybook so that component that depend on LL are working property within storybooks
=> fix: settings / contact support appearance modal screen

app/components/balance-header/balance-header.tsx
This PR fixes the issue where the state of the primary balance (hidden <-> not hidden) changes between screen transitions.
=> chore: fix hide primary balance

app/screens/send-bitcoin-screen/use-send-payment.ts
I don't quite get yet how all the send flow is working from a type perspective and the `sendPayment`, `sendPaymentFn` and `useSendPayment` and how it's flowing between screen and where argument are been set
in essence, the goal of this PR is to add `refetchQueries` as an argument to the payment mutation, but I don't think this is where it should be set because I would guess the argument are been passed somewhere else. 
I think my approach may work but @UncleSamtoshi can you double check?
=> fix: refresh on send

android/app/build.gradle
not sure why implication this may have on the build if new build on a same arch have lower version
=> chore: make it possible to parse build number more easily

android/app/build.gradle
this change is to be able to use react native debugger
currently there are some issues around using react native debugger with hermes.
so hermes should be deactivated when someone wants to use this tool, but the intl flavor needs to be used
=> chore: use -intl version of js for jsc

app/graphql/analytics.tsx, app/graphql/generated.gql, app/graphql/generated.ts, app/screens/home-screen/home-screen.tsx
chore: separate tx query from the rest of the query
this allow to not reset the cache for tx for now on home refresh. this is a tradeoff because now all but the tx are been refetch from the home screen on refresh (ie: scroll down to show the "refresh" wheel)
I also increase the number of tx to 12 so that when someone move to tx they can see the first screen fully populated while the other transactions are been fetched in the background
=> chore: misc queries improvments

app/graphql/cache.ts, app/graphql/generated.gql, app/graphql/generated.ts, app/screens/receive-bitcoin-screen/receive-wrapper.tsx, app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx, ios/Podfile.lock
by fetching `realtimePrice`, we will automatically update the cache. 
if the price is stealth for whatever reason (websocket issue -- something else to debug), then we will have a very recent price in memory.
=> chore: force price refresh when sending/receiving a payment

app/screens/receive-bitcoin-screen/receive-usd.tsx
- only show invoice expiration if remaining time is less than an hour
=> chore: incorrect invoice expiration

.storybook/storybook.requires.js, app/graphql/cache.ts, app/graphql/generated.gql, app/graphql/generated.ts, app/hooks/use-display-currency.ts, app/hooks/use-price-conversion.ts, app/navigation/stack-param-lists.ts, app/screens/receive-bitcoin-screen/receive-btc.tsx, app/screens/receive-bitcoin-screen/receive-usd.tsx, app/screens/receive-bitcoin-screen/receive-wrapper.stories.tsx, app/screens/receive-bitcoin-screen/receive-wrapper.tsx, app/screens/settings-screen/display-currency-screen.tsx
- adding storybook for receive screen. only query on loaded up been mocked right now. 
- removing the backward compatibility with pre-USD wallet (when I see them). I don't think we want to maintain the complexity of having BTC only wallet going forward. it adds boilerplate. if someone wants a BTC only wallet then they can fork and adapt the code.
=> chore: first version of storybook for receive screen

app/screens/galoy-address-screen/galoy-address-screen.tsx, app/screens/galoy-address-screen/set-address-modal.tsx
This fix ensures that when the user sets his/her username, we query for an update is that when the user presses the back or home button, the `set address` modal is not rendered as we currently have it.
=> fix: set username issue in address screen

.circleci/config.yml
This will disable the test in pr workflow on the main branch as it's redundant: we do it via concourse on every merge to main anyway.
=> ci: disable circleci test_in_pr workflow on main

app/graphql/generated.gql, app/graphql/generated.ts, app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- use btcwallet as default for onchain payments
- alert user when selecting a usd wallet that it is not supported for onchain
=> fix: prevent usd wallet for onchain send

app/graphql/generated.ts, app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- fixes issue when switching between usd and btc wallets in the send flow where the currency was stuck in the settlement amount for the previous wallet
=> fix: send flow when switching wallets

.github/workflows/conventional.yaml
as we get more open source contributions, we want to enforce the convention commit rules. so adding a github action for it.
=> ci: test conventional commit

ci/pipeline.yml, ci/tasks/bump-testflight-to-beta-pr.sh, ci/tasks/helpers.sh, ci/tasks/prerelease.sh, ci/tasks/upload-to-app-store.sh
- push the newer tag early
- find the tag from gcs url
- use the tag on circleci and bump task cross checks
=> ci: fix issues with release versions

.storybook/views/story-screen.tsx, __tests__/config/galoy-instances.spec.ts, __tests__/persistent-storage.spec.ts, android/gradle.properties, app/components/balance-header/balance-header.tsx, app/components/stablesats-modal/stablesats-modal.tsx, app/config/appinfo.ts, app/config/galoy-instances.ts, app/graphql/client.tsx, app/hooks/use-app-config.ts, app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/debug-screen/debug-screen.tsx, app/screens/phone-auth-screen/phone-input.tsx, app/screens/transaction-detail-screen/transaction-detail-screen.tsx, app/store/persistent-state/index.tsx, app/store/persistent-state/state-migrations.ts, e2e/01-welcome-screen-flow.e2e.spec.ts
- less bloated implementation of PersistentState:
-- only store id, token (and custom property if `id === Custom`)
-- for default network, use value from Array instead of story them
--- will make it easier to change bank name (ie: for forks)
--- less need for migration going forward
-- custom property like theme or Modals  like stablesatsModals who have been discarded will be stored eventually as apollo-client client-only data. not that critical if the value are been reseted eventually
- fix https://github.com/GaloyMoney/galoy-mobile/issues/684
-- TODO in a future PR: do not reset the apollo-client on every app update. but only on schema changes.
=> chore: refactoring persistent state

__tests__/hooks/use-display-currency.spec.tsx
- adding test for useDisplayCurrency
- using a different pattern than the tests used for usePriceConversion (we should eventually converge to way of mocking up the gql calls)
-- Note that I ran into some randomness issue with mocking. if the tests for the 0 digits is at the end, it's failing. not sure why but now re-order solves it. 
maybe more function can be tests on this hooks. this is a start.
=> tests: first test for useDisplayCurrency

__tests__/screens/send-confirmation.spec.tsx, app/components/money-amount-input/index.tsx, app/hooks/use-display-currency.ts
- if a currency's dollar has less value than a usd cent, do not display decimals
=> feat: hide decimals for inflated currencies

app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
issue: if one were to scan a QR code, but this is not the correct QR code (ie: amount has not been set, and the merchant show another QR code where the amount is set), the user would have to go back. 
there is some state when this happens, scanning the new QR code doesn't work anymore, it's becoming a no-op.
I think this is the best way to address this bug.
=> fix: state issue when scanning QR code and going back

app/app.tsx, app/graphql/client.tsx, app/graphql/network-error-component.tsx, app/graphql/network-error-context.ts, app/screens/error-screen/error-screen.tsx
following improvement has been made:
On the UX side:
- convert Toast to Alert. if someone is logged out, it should be a persistent message they tap on to understand what is going on
- go back to the home screen once the user tap the Ok button.
on the network side:
- `logout` happen immediately, not after the user press Ok or when the Toast hide (limit the number of 401)
- if the error is 401, we don't retry it
it's still possible to get a couple of 401 because some requests are sent concurrently. but we're going from 20+ requests to the backend, to 1 to 3 based on my local tests. 
fix #1867
=> fix: properly manage 401 response code

app/screens/conversion-flow/conversion-confirmation-screen.tsx
- show the error message in the conversion screen, instead of eating it and feeling like a no-ip where an error message was return (click on the button but do/show nothing on error)
=> fix: error message not showing properly on conversion confirmation screen

ios/Podfile.lock, package.json, yarn.lock
There is an issue with the minimum deployment target for ReactNative Codegen after upgrading xcode to v14.3 (see here https://github.com/facebook/react-native/issues/36690). it throws an invalid value error when building the app on ios. The issue has been fixed in this patch release https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0716. 
Alternatively, you can bump it manually in your ReactNative codegen pods build settings of xcode.
=> fix: upgrade reactnative to 0.71.6 to fix issue with xcode 14.3

app/graphql/client.tsx, app/graphql/network-error-component.tsx, app/graphql/network-error-context.ts
- reverts 401 modal changes and instead gives special retry mechanism for 401 errors before logging the user out
- reorder retryLink so that it runs before the errorLink, in the past we set the error before we even retried, this should retry first and then if it still fails it will set the network error (it should help with the 502 errors we are seeing)
=> fix: prevent infinite 401 loop

ios/Gemfile, ios/Gemfile.lock
use fastlane 2.212.1 until this issue is fixed https://github.com/fastlane/fastlane/issues/21207
This will unblock the mobile deployment pipeline
=> chore(ci): use fastlane v2.212.1

ci/pipeline.yml, ci/tasks/choose-commit-prerelease.sh, ci/tasks/upload-gh-prerelease-asset.sh
Because dev builds were getting uploaded with commit ids as build numbers. This is more appropriate.
Already applied.
Works: https://ci.galoy.io/teams/dev/pipelines/galoy-mobile/jobs/upload-gh-prerelease-asset/builds/2
=> ci: have prod builds as prerelease assets

app/components/floor-tooltip/floor-tooltip.tsx, app/graphql/generated.ts, app/screens/send-bitcoin-screen/destination-information.tsx, app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
Adds dark mode support to send bitcoin screen.
How Dark Mode looks:
How Dark Mode handles error:
=> feat: send bitcoin screen dark mode support

app/components/screen/screen.tsx
Fix issue #2208
**Preview**
I haven't changed the earn screen to blue or green
if we want to match it with the background, then the earn screen also scrolls, and when we scroll the background color changes, should I change the notification bar color on scroll?
=> fix: changed notification bar color on mode change

ci/pipeline.yml
- also added a previously removed release pipeline task config to properly repipe
Already applied
=> ci: use local node 18 image for e2e tests, increase timeout for android and ios builds

ci/pipeline.yml
Applied, attempt to fix:
```
fatal: ambiguous argument '2.2.52': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
=> ci: fetch tags in prerelease

.circleci/config.yml
This reverts commit acd36aac50ba5ba603f036c4d0305e608d920288.
=> chore: Revert "chore: attempt to use new m1 ressources (#2257)"

.storybook/storybook.requires.js, .storybook/storybook.tsx, app/graphql/cache.ts, app/graphql/client-only-query.ts, app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/navigation/root-navigator.tsx, app/navigation/stack-param-lists.ts, app/screens/settings-screen/settings-screen.tsx, app/screens/settings-screen/theme-screen.stories.tsx, app/screens/settings-screen/theme-screen.tsx, app/utils/theme-sync.tsx
- Theme can now be switched from settings.
- Added a new `System` theme which responds to dark/light mode as set at OS and changes at runtime too
- Removed Beta tag for Dark Mode
<table>
<tr>
<td><img src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/b827556a-f545-498e-a7a0-357aa819566b" alt="Image 1" style="width: 100%;"/></td>
<td><img src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/5c5291a2-b05c-4571-80e4-07b88f4f471b" alt="Image 2" style="width: 100%;"/></td>
<td><img src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/b31bd07c-8354-4c41-b922-f2c23a1ef9f4" alt="Image 3" style="width: 100%;"/></td>  </tr>
</table>
=> feat: switch themes

.circleci/config.yml
this would avoid issues like this one: https://app.circleci.com/pipelines/github/GaloyMoney/galoy-mobile/8698/workflows/a6918e71-054b-4714-b0f8-7626921ae946/jobs/12789
=> chore: avoid Could not install WWDR certificate issue in tests

app/app.tsx, app/config/feature-flags-context.tsx
currently the secondary button label change after 1 sec
this PR would preserve the "blink" loading screen from RNBootSplash until the call to the the remote config server has resolved
=> chore: prevent button flickering on app start

app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/transaction-detail-screen/transaction-detail-screen.tsx
This is how the screen will look when an Onchain Transaction returns `null` transactionHash
=> feat: handle onchain transaction hash null for pending unbroadcast state

app/components/contact-modal/contact-modal.tsx, app/components/contact-support-button/contact-support-button.tsx, app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/settings-screen/settings-screen.tsx
Fixes issue #2384 by removing telegram from the available support options when user taps "Need help".  Instead I've added a "Join the community" option on the main settings menu which also includes a link to mattermost.  I've utilised the existing `supportChannelsToHide` prop on the ContactModal to show/hide either 1:1 support options or community options.  I also changed the ContactModal which is available through the ContactSupportButton which is currently only used on the PhoneInput.  
Example screenshots below:
=> fix: Fix contact options

__tests__/payment-details/helpers.ts, __tests__/payment-details/no-amount-onchain.spec.ts, app/components/amount-input/amount-input.tsx, app/components/atomic/galoy-tertiary-button/galoy-tertiary-button.tsx, app/graphql/generated.gql, app/graphql/generated.ts, app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/send-bitcoin-screen/payment-details/index.types.ts, app/screens/send-bitcoin-screen/payment-details/lightning.ts, app/screens/send-bitcoin-screen/payment-details/onchain.ts, app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx, app/screens/send-bitcoin-screen/use-send-payment.ts
This PR adds the feature of sending all of an user's bitcoin/stablesats usd onchain. It uses the `onChainPaymentSendAll` mutation supported by the backend. It's a flow only available in "onchain" payment.
<table>
<tr>
<td>Selected USD Wallet</td>
<td>Tapped "Max Amount" button</td>
<td>Details Screen</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Supersedes https://github.com/GaloyMoney/galoy-mobile/pull/1670
PS: It uses @UncleSamtoshi's payment detail logic layer for the send all handling so a review from him would be awesome.
=> feat: send all onchain

app/components/wallet-overview/wallet-overview.tsx
This PR is to fix spacing around the main home screen wallet overview component.
<table>
<tr>
<td></td>
<td>Earlier</td>
<td>Fix (this PR)</td>
</tr>
<tr>
<td>With Display Currency</td>
<td><img src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/2d5823e5-8384-4e0b-9e7c-733f81610e40"/></td>
<td><img src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/f51161a0-6833-4dc4-a9ad-5a8949e864b4" /></td>
</tr>
<tr>
<td>Without Display Currency</td>
<td><img src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/31d28cb0-0075-430d-97a9-544022461807" /></td>
<td><img src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/d59959ab-955c-414b-832a-c43b77b44925" /></td>
</tr>
</table>
This issue and it's fix is more vividly visible when I have highlighted the …
=> fix: spacing around wallet overview

app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx, app/screens/send-bitcoin-screen/use-send-payment.ts
- only allow one attempt at sending a payment
- show a success message if payment status is `valid`
=> fix: prevent multiple sends

app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx, ios/GaloyApp.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, yarn.lock
This fixes #2670.  This library provides error codes in the callback that you can inspect and respond to, but this library also doesn't seem to need permissions for the photo library (at least it didn't for any of my emulators).
https://github.com/react-native-image-picker/react-native-image-picker#ErrorCode
=> fix: Fixed error on scan screen permissions

android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml, package.json
I couldn't replicate the issue but reading on the docs, PermissionsAndroid are a list of specified dangerous permissions that prompts the user. The POST_NOTIFICATION key is not present in the manifest. This adds that.
I'm not 100% sure that it would fix the issue but I feel this is a step in the right direction.
=> fix: post notification issue

android/fastlane/Fastfile
fixes the submit interval
This is needed for Huawei rollout
I have applied it manually so that the last version got rolled out
=> chore: submit interval for huawei

app/screens/receive-bitcoin-screen/qr-view.tsx
value was changed from 260 to 195 in the receive screen refactoring
why was it changed? some issues with some particular devices?
https://github.com/GaloyMoney/galoy-mobile/blame/main/app/screens/receive-bitcoin-screen/qr-view.tsx#L139C19-L139C19
=> fix: QR code too small to be scan on my old LG

.storybook/views/story.tsx, app/components/custom-modal/custom-modal.tsx, app/components/modal-tooltip/modal-tooltip.tsx, app/components/screen/screen.tsx, app/components/set-default-account-modal/set-default-account-modal.tsx, app/components/stablesats-modal/stablesats-modal.tsx, app/rne-theme/colors.stories.tsx, app/screens/conversion-flow/conversion-confirmation-screen.tsx, app/screens/earns-screen/earns-quiz.tsx, app/screens/home-screen/home-screen.tsx, app/screens/people-screen/circles/circles-dashboard-screen.tsx
using the ScrollView from react-native-gesture-handler make my android device works better
without it, at some occasion, when I would attempt to scroll, the scroll action would instead close and come back to the previous screen
@sandipndev maybe this would have some effect on the test when going to the debug screen?
=> fix: scrolling issue on android

app/screens/send-bitcoin-screen/payment-destination/lnurl.ts
When sending with lnurl-p, on the 1st request a response with `min` and `max` value is returned for the lnurl endpoint. This PR is to auto-populate the send amount field with the lnurl min instead of `0`.
=> refactor: use lnurl min to populate default send amount

__tests__/payment-details/helpers.ts, __tests__/payment-request/payment-request-creation-data.spec.ts, app/screens/conversion-flow/conversion-details-screen.tsx, app/screens/receive-bitcoin-screen/payment/payment-request-creation-data.ts, app/screens/receive-bitcoin-screen/use-receive-bitcoin.ts
this previously was showing a forever loading screen when trying to add an amount with stablesats + onchain
fix #2772
=> fix: deactivate setting an amount for onchain + stablesats

app/screens/earns-screen/earns-quiz.tsx
This addresses issue #2808. 
It took a long time to figure out which 'touchable' wrapper would work for this. I settled on 'Pressable' but this will need to be tested on a couple physical devices (Android and iOS) in order to confirm that everything is okay.
I tested it on an Android G20 and an iPhone 8 and it was greatly improved.
@pretyflaco
=> fix(earns-quiz): improved scrolling in quiz section Modal

app/screens/earns-map-screen/earns-map-screen.tsx
Was anyone else experiencing this crash? Number() call was always returning NaaN cause it had invalid data for the arg.
=> fix: percentage symbol must be outside of 'Number()' call

app/screens/galoy-address-screen/address-explainer-modal.tsx, app/screens/galoy-address-screen/paycode-explainer-modal.tsx, app/screens/galoy-address-screen/pos-explainer-modal.tsx
addresses issue: #2888 
swap react-native-gesture-handler TouchableOpacity component for react-native version
=> fix(galoy-address-screen): make close 'X' button touchable in some modals

app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/send-bitcoin-screen/confirm-destination-modal.tsx, app/screens/send-bitcoin-screen/destination-information.tsx, app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-reducer.ts
Closing the old PR #2909 in order to separate it into 2 separate PRs that address different things.
This PR makes a few UI improvements to the send bitcoin destination screen:
- fix 1px jump from borderWidth on pasting
- Buttons didn't have opacity indication when being pressed
- Added a toast so users know what's happening when they press the paste button (I was confused when I was trying to press it and I didn't have anything in my clipboard. Initially thought it was broken)
- Pressing the paste button twice was messing up the validation process and removing it on 2nd press (it went into manual 'entering' mode)
- multiple seconds of lag after pressing paste button on android
@nicolasburtey This PR has been updated with all the code changes you requested on the previous PR
=> Feat(send-bitcoin-destination-screen): UI improvements

app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
Made as a substitute solution for issue #2298 
Allows for the the user to copy to clipboard on the send bitcoin screen. This is done here because it's really only a desired behaviour when the user has gotten to this screen from scanning a QR.
=> feat: Can copy destination on send bitcoin screen

app/components/invite-modal/invite-modal.tsx, app/graphql/generated.gql, app/graphql/generated.ts, app/screens/people-screen/circles/circles-dashboard-screen.tsx, app/screens/people-screen/circles/invite-friends-card.tsx, app/screens/totp-screen/totp-registration-initiate.tsx, app/screens/totp-screen/totp-registration-validate.tsx, supergraph.graphql
Steps to reproduce the original issue:
- Go to `AllContactsScreen`
- Click back button
The cause:
- The cache was being overwritten by queries without the object id present, this was causing the `contacts` field of me to be undefined when clicking back on the `AllContactsScreen`, `slice()` was then called on `undefined` leading to an error being thrown
- It is also a symptom of using `cache-and-network` fetch policy hiding type issues for when the cache is corrupted or altered by a different query
Fix:
- add `id` field to gql queries
=> fix: crash from cache

app/screens/people-screen/people-screen.types.d.ts, app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
| Light Theme | Dark Theme |
|:-----------:|:----------:|
| ![Light AR](https://github.com/GaloyMoney/galoy-mobile/assets/32636827/93e2c050-6987-42a1-b022-f5b11e180525) | ![Dark AR](https://github.com/GaloyMoney/galoy-mobile/assets/32636827/2b458ebf-309a-40f3-9af6-6f62ac89b9f4) |
---
| Light Theme | Dark Theme |
|:-----------:|:----------:|
| ![Light ARMO](https://github.com/GaloyMoney/galoy-mobile/assets/32636827/1ac05d5b-8457-4a06-b9e4-5497c6d21be2) | ![Dark ARMO](https://github.com/GaloyMoney/galoy-mobile/assets/32636827/8006c8fe-2588-4e6d-ae15-e974e410288b) |
---
| Light Theme | Dark Theme |
|:-----------:|:----------:|
| ![Light ARNO](https://github.com/GaloyMoney/galoy-mobile/assets/32636827/87ff1ed3-f8ed-410c-8d17-a3bb56c2e4f8) | ![Dark …
=> feat(blip-16): display recently used contacts for quick send

app/screens/receive-bitcoin-screen/receive-screen.tsx
Fixes #2939 
As you can see below, there's several other fields that need to be fixed for boomer text. Nonetheless, this fixes the section that was requested in the issue.
=> fix: bitcoin address on receive payment screen can use ellipsis

app/components/galoy-toast/galoy-toast.tsx
Fixes #2947 
Toasts have responsive height now instead of static. Added some vertical padding to ensure smaller toasts look nice
=> fix: toasts now have responsive height

app/graphql/generated.ts, app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/authentication-screen/authentication-screen.tsx
Fixes #2871. Also went ahead and made the 3 minor changes/bugfixes I suggested in https://github.com/GaloyMoney/galoy-mobile/issues/2871#issuecomment-1869816859. For the 3rd one I opted to add an informative message to the confirmation modal that logging out will clear the user's cache and user settings.
=> feat: added confirm modal before logout

android/app/src/main/AndroidManifest.xml, app/config/appinfo.ts, app/navigation/navigation-container-wrapper.tsx, ios/GaloyApp/Info.plist
With this, if you do `blink://circles` you will get inside the circles screen directly.
This pattern can also be used to [useLinkTo](https://reactnavigation.org/docs/use-link-to) any screen with push notifications.
=> chore: improve deep linking

ios/Gemfile
App Store Upload was causing error: "A parameter has an invalid value - 'prices' is not a valid relationship name"
Fixed using https://github.com/fastlane/fastlane/issues/21819
=> fix: fastlane issue with app store upload

app/components/push-notification/push-notification.tsx, app/navigation/navigation-container-wrapper.tsx
With this PR, you can send an extra `linkTo` in the data of the notification packet to open the specific screen.
---
Builds on https://github.com/GaloyMoney/galoy-mobile/pull/3004#issuecomment-1894172245
@agbegin With this we can do the following deep links:
| Link | Screen |
|---|---|
| blink://home | Home Tab |
| blink://people | People Tab |
| blink://people/circles | Circles Screen |
| blink://earn | Earn Screen |
| blink://map | Map Screen |
| blink://receive | Receive Screen |
| blink://convert | Conversion Screen |
| blink://scan-qr | Scan QR Screen |
| blink://transaction/:txid | Transaction Screen with the User's Transaction ID (Blink Internal ID) |
| blink://:address | Send to Bitcoin Onchain Address / LNURL Address |
Do you guys feel there are any more screen needed to …
=> chore: deep link all pages

app/components/payment-destination-display/payment-destination-display.tsx, app/screens/send-bitcoin-screen/destination-information.tsx, app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
Addresses #2979 
Plus three other minor ui fixes:
- marginBottom on destination input shouldn't be there. Moved it to marginTop for the error message and the contacts list
- flex: 1 for destination input field in both scenarios (short and long text). Ensures copy button is at the far end of the container
- contact should deselect when a QR code or a Paste is done
Should note that the refactor required for the destination input to be sent as a parameter. The **autovalidation** flow was slightly refactored to follow suit, as well as normal presses of the 'Next' button. They manually input **route.params.payment** or **destinationState.unparsedDestination** respectively now.
=> feat: pressing contact immediately goes to next screen

app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
if the server return commentAllowed = 0 or false in the prior request, and a comment it still send nonetheless, then requestInvoice may be fail (at least this is the default behavior with lnbits)
fix #3029
=> fix: passing comment to requestInvoice should be optional

.circleci/config.yml
Addresses the following feedback received from App Store Connect:
=> chore: update ios sdk used to build app

app/screens/webview/webview.tsx
+ Fixed: Change WebView theme to match the app's theme. Previously, if the system theme was set to light but the app's theme was dark, the WebView theme would remain light. With this PR, the WebView theme will align with the app's theme.
--- to --->
+ Fixed: Back button for webview.
=> fix: webview back button, webview dark-mode on android

.detoxrc.js, .envrc, .github/workflows/e2e.yml, .gitignore, Makefile, README.md, docs/dev.md, flake.lock, flake.nix, ios/GaloyApp.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json
This PR installs all required Android SDKs, Ruby, Cocoapods, Fastlane and all required build tools in a deterministic manner using Nix Flakes. Unfortunately, Xcode can't be automatically installed because Apple License lets only Apple serve Xcode binaries (needs authentication into your Apple Account) but the setup of installing the right version of Xcode has been added in this PR.
This PR also brings in the necessary documentation to do any dev work in a simpler and faster manner for this repo.
----
1. Checkout this PR
2. Enable direnv hook and run direnv allow (~1.5GB download for Android SDK)
4. Run `yarn install`
5. Run `yarn start` in one terminal.
6. Android: Run `make emulator` on one terminal and `yarn android` in another. If you get "error Failed to launch emulator." in the yarn …
=> chore: nixify react native setup

app/assets/icons-redesign/arrow-left.svg, app/components/atomic/galoy-icon/galoy-icon.tsx, app/components/atomic/galoy-slider-button/galoy-slider-button.tsx
Fixes #3055 
I could reproduce the bug and slider button to confirm the transaction was stuck in the left corner.
Now, I have fixed this to move from the right to left direction, changed the button icon to the left arrow, and fixed the slider text animation.
Here is how it works now:
https://github.com/GaloyMoney/galoy-mobile/assets/17739006/fca2f433-8961-42aa-8877-3b50816258c4
=> fix: confirm payment slider bug in rtl layouts

app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
Fixes #3128
Show an alert to open a URL when QR encodes a URL instead of showing an invalid address error.
=> feat: Add link opening functionality in ScanningQRCodeScreen

ios/GaloyApp.xcodeproj/project.pbxproj, ios/PrivacyInfo.xcprivacy
Fix for this issue with rollout:
=> fix(ios): missing api docs for NSPrivacy

app/components/invite-modal/invite-modal.tsx
fix #3204
cc @sandipndev @UncleSamtoshi border around QR code should always be white
=> fix: border for circle card

app/screens/home-screen/home-screen.tsx, app/screens/notification-history-screen/notification.tsx
Previously it was hardcoded to 1
=> chore: transaction list home screen adaptive to screen size

app/graphql/generated.gql, app/graphql/generated.ts, app/screens/notification-history-screen/notification-history-screen.tsx, app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
Fixes #3081 
Added a `PanGestureHandler` which captures slide gestures in areas surrounding the confirm slider button. This prevents the native navigation handler from catching this event, and back action is not triggered.
**Demo:**
https://github.com/GaloyMoney/blink-mobile/assets/17739006/91ae2854-9160-4dcf-b6a2-879e176cba15
=> feat: disable slide gesture around confirm slider button

app/components/notifications/bulletins.tsx, app/components/notifications/notification-card-ui.tsx, app/graphql/generated.gql, app/graphql/generated.ts, app/screens/home-screen/home-screen.tsx, app/screens/notification-history-screen/notification-history-screen.tsx, app/screens/notification-history-screen/notification.tsx
=> feat: add icons to notifications and bulletin

ios/Podfile.lock, package.json, yarn.lock
may help with issue like https://github.com/GaloyMoney/blink-mobile/issues/3256
=> chore: updating RN vision camera package

app/components/price-history/price-history.tsx, app/graphql/generated.gql, app/graphql/generated.ts, app/screens/home-screen/home-screen.tsx, app/screens/price/price-history-screen.tsx, e2e/06-other-tests.e2e.spec.ts
- allow hovering over prices
- use price of 1 btc
=> feat: reactive price screen

app/components/june-challenge/card.tsx, app/components/june-challenge/index.tsx, app/components/june-challenge/modal.tsx, app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/i18n/raw-i18n/translations/es.json, app/screens/people-screen/circles/circles-dashboard-screen.tsx, app/utils/date.ts
Fixes #3260
Adds June Blink circles challenge
=> feat: add june challenge modal

app/components/currency-keyboard/currency-keyboard.tsx
Fixes #3244 
Long press backspace to continuously delete numbers
[Screencast from 25-05-24 04:42:31 PM IST.webm](https://github.com/GaloyMoney/blink-mobile/assets/17739006/3f5cbbc5-3fb8-4d5b-bf28-c0f902674923)
=> feat: Add backspace long press functionality to currency keyboard

app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/screens/earns-screen/earns-quiz.tsx, app/screens/earns-screen/earns-section.tsx
Fixes #3229 
Change pluralization of "sat" based on the amount. If amount is 1 then `formattedAmount` is **"1 sat"** else **"n sats"**
=> fix: pluralization in earn screen

app/screens/phone-auth-screen/phone-login-validation.tsx, app/screens/phone-auth-screen/phone-registration-validation.tsx
Almost all users request the phone code between 2 and 4 times (with the data after the last backend updat...e this can be the main reason to message cost). This PR updates waiting time from 30 to 150 secs (2.5 mins)
https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/bre758WPtdS
=> chore: update waiting for code time

.storybook/views/story-screen.tsx, __tests__/persistent-storage.spec.ts, app/hooks/use-app-config.ts, app/store/persistent-state/state-migrations.ts
Token management for #3273 
- Update PersistantState schema to have a list of saved tokens for multiple accounts
- Create migrations for the same
=> feat: store multiple tokens

flake.nix
Previous behavior: Apple silicon users would clone the repository and try to run the application on an IOS emulator. The application would not launch if Rosetta2 is not installed and throw the following error: The request was denied by service delegate (SBMainWorkspace)
New behavior: The flake.nix checks if the user
- is on MacOS
- has an Apple Silicon chip
- does not yet have Rosetta2 installed
If all of the above holds, the flake prompts the user to install Rosetta2 and agree to the license by executing the following command: `sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license` and in a last step checks if the installation has been successful.
=> fix(dev): Check for Rosetta2 and install if necessary (MacOS)

app/screens/settings-screen/settings/account-pos.tsx, app/screens/settings-screen/settings/account-static-qr.tsx
Fixing the issue where the `LnAdressHostname` is displayed in place of the `posUrl`
The correct address for the Pos and StaticQR should  start with `pay.blink.sv`:
=> fix: always show full address for pos and static qr in settings

ios/GaloyApp/GaloyApp.entitlements, ios/GaloyApp/GaloyAppDebug.entitlements
use old team id to avoid provisioning profile issues
=> fix: kvstore identifier

ios/GaloyApp/GaloyApp.entitlements, ios/GaloyApp/GaloyAppDebug.entitlements
rollback when build is successful
=> chore: remove keychain-access-groups

android/app/src/main/AndroidManifest.xml, app/navigation/navigation-container-wrapper.tsx, ios/GaloyApp/Info.plist
Adding the missing:
`"android.intent.action.VIEW"`
and
`"android.intent.category.BROWSABLE"`
to the `lnurlw` and `lnulrp` schemes
Apply same behaviour for links opened in browser or through NFC.
=> chore: extend and consolidate deep links in AndroidManifest

__tests__/screens/transaction-history-screen.spec.tsx, app/components/wallet-filter-dropdown/index.ts, app/components/wallet-filter-dropdown/wallet-filter-dropdown.tsx, app/graphql/generated.gql, app/graphql/generated.ts, app/graphql/mocks.ts, app/i18n/en/index.ts, app/i18n/i18n-types.ts, app/i18n/raw-i18n/source/en.json, app/i18n/raw-i18n/translations/es.json, app/screens/transaction-history/transaction-history-screen.tsx
This Pull Request introduces a new **transaction filter** feature to the **Transaction History** screen. Users can now filter their transactions by wallet type:
- **ALL** (default): Shows all transactions, regardless of whether they are BTC or USD. This maintains the original behavior of the screen.
- **BTC**: Displays only transactions associated with the BTC wallet.
- **USD**: Displays only transactions associated with the USD wallet.
This improvement enhances the user experience by allowing more precise transaction browsing based on wallet type.
=> refactor: redesign transaction history
