blinkbitcoin/blink-mobile

- app/components/large-button/large-button.tsx
- app/components/transaction-item/transaction-item.tsx
Possible workaround for issue #49
> nest avatar and title in ListItem

- app/components/mountain-header/mountain-header.tsx
- app/i18n/en.json
- app/i18n/es.json
- app/screens/earns-map-screen/earns-map-screen.tsx
- app/screens/earns-screen/section-completed.tsx
Implements #53 . You may want to double check some of my translations such as "Usted Ganó" for "You Earned." I also changed the font size in textStyleBox from 18 to 16 because the Spanish translations were larger and hitting the borders of "BoxAdding."
> Spanish quiz translation integration

- ios/Podfile.lock
- package.json
- yarn.lock
Was getting an error on start up:
`The following build commands failed:
MergeSwiftModule normal x86_64
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler`
Updated lottie-react-native preventing error in the future.
> Updated lottie-react-native to fix start up error

- app/screens/authentication-screen/pin-screen.tsx
Fixes the issue with too many attempts on the pin screen not routing back to the home screen.
> import sleep

- app/graphql/query.ts
- app/navigation/root-navigator.tsx
- app/screens/authentication-screen/authentication-check-screen.tsx
- app/screens/authentication-screen/authentication-screen.tsx
- app/screens/authentication-screen/pin-screen.tsx
- app/utils/clipboard.ts
> Call checkClipboard after authentication

- app/components/modal-clipboard/modal-clipboard.tsx
- app/graphql/client-only-query.ts
- app/navigation/root-navigator.tsx
- app/screens/authentication-screen/authentication-check-screen.tsx
- app/screens/authentication-screen/authentication-screen.tsx
- app/screens/authentication-screen/pin-screen.tsx
- app/utils/clipboard.ts
> Cache last valid payment in clipboard

- app/i18n/en.json
- app/i18n/es.json
@jrbuhl93 apologies for the messy PR, you just need to check the latest commit changes
- first commit: only sort of the keys in the translation files (no content changes) https://github.com/GaloyMoney/galoy-mobile/commit/d1029f41e5fb01d4f995d963a921c175ffd0f5be 
- Add missing translations, fix some translations https://github.com/GaloyMoney/galoy-mobile/pull/112/commits/029bfb4ba8005569eb9205e810dabb556c1d0b2a
> Fix es translations

- app/components/price-graph/price-graph.tsx
- app/constants/support.ts
- app/graphql/cache.ts
- app/i18n/en.json
- app/i18n/es.json
- app/navigation/root-navigator.tsx
- app/screens/earns-map-screen/bottom-ongoing-01.en.svg
- app/screens/earns-map-screen/bottom-ongoing-01.es.svg
- app/screens/earns-map-screen/bottom-start-01.en.svg
- app/screens/earns-map-screen/bottom-start-01.es.svg
- app/screens/earns-map-screen/earns-map-screen.tsx
- app/screens/earns-screen/earns-quiz.tsx
- app/screens/earns-screen/earns-section.tsx
- app/screens/map-screen/map-screen.tsx
- app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/screens/welcome-screens/welcome-screens.tsx
- tsconfig.json
Adds translations for text in en.json requested in #113. Also adds a structure for dynamically importing svgs based on React.lazy. The dynamics imports used required me to upgrade from es2015 to es2020 in ts.config.json for the field 'module'.
> Add translations

- app/components/input-payment/input-payment.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx
- ios/Podfile.lock
Fixes issue #99. Thoughts on the new size?
> Increase input payment font size to 28rem

- __tests__/currency-conversion.ts
- app/app.tsx
- app/utils/polyfill.ts
- package.json
- yarn.lock
This got lost when I rebased #106. Adding it back in here for another immediate release.
> Add polyfill

- app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx
Adds the feature requested in #143.
https://user-images.githubusercontent.com/35902932/128708899-eb24fc5a-728e-4c4d-94f3-b3e25bdf7722.mp4
> Add camera icon for scan QR navigation

- app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx
> Call setInteractive(true) in send reset

- __tests__/screens/__snapshots__/send-bitcoin-screen.spec.tsx.snap
- app/components/input-payment/input-payment.tsx
Fixes #148. Also refactored the icons into functions to make the JSX more readable.
> Always set InputPayment cursor position to displayValue length

- app/utils/biometricAuthentication.ts
Fixes a glitch on some brands of Huawei phones Kartik found where the screen will freeze if you request biometric authentication multiple times rapidly.
> Add check if biometric authenticate is in progress

- app/app.tsx
- app/graphql/graphql-v2-operations.ts
- app/screens/debug-screen/debug-screen.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- app/utils/token.ts
- ios/Podfile.lock
Added a split to ApolloClient links so that we use `userRequestAuthCode` and `userLogin` from the new graphql api.
> V2 schema for phone auth

- app/components/modal-clipboard/modal-clipboard.tsx
- app/i18n/en.json
- app/i18n/es.json
For the modal clipboard and hide balance feature.
> Spanish translations

- app/screens/map-screen/map-screen.tsx
- Removed old pin for user location
- Use showsUserLocation within MapView comp
Fixes https://github.com/GaloyMoney/galoy-mobile/issues/122
> Improve pin for current location

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- android/build.gradle
- app/i18n/en.json
- app/i18n/es.json
- app/screens/phone-auth-screen/phone-auth.tsx
- ios/Podfile.lock
Fixes #186 
**Changes**
- Now shows toast error message to user when too many requests error is received for `userRequestAuthCode` call is made
> Fix too many auth code requests error

- app/i18n/en.json
- app/i18n/es.json
- app/screens/contacts-detail-screen/contacts-detail.tsx
- app/screens/transaction-detail-screen/transaction-detail-screen.tsx
Should fix #200 
I haven't tested the screens locally as my local DB seems to be broken and I'm getting index errors.  If I get time tomorrow I'll test it.
> Fix username transaction translations

- app/screens/debug-screen/debug-screen.tsx
Needed to update the in-memory network stored in the authtoken,
> Reload auth token when network is saved

- app/screens/contacts-screen/contacts.tsx
> Add an array of filtered contact names

- app/graphql/graphql-v2-operations.ts
- app/graphql/query.ts
- app/screens/map-screen/map-screen.tsx
Loads the merchants on the map separate from the mainQuery using the v2 api.
> Add businessMapMarkers to v2 api

- ios/fastlane/Appfile
- package.json
Removing `jb` from Galoy publishing details for apple.  Now published under my account.
> Update publishing info

- app/i18n/en.json
- app/i18n/es.json
- app/screens/contacts-screen/contacts.tsx
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- package.json
- yarn.lock
Fixes:
#268 
#267 
#261 
#276 
#275
> V2 fixes david

- app/i18n/es.json
@dolcalmi suggested a change to the Spanish translation of this error message.
> Updated translation

- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
> Fixed undefined error

- android/app/src/main/java/com/galoyapp/MainApplication.java
- android/settings.gradle
- ios/Podfile
Some icons were missing during device testing on android (although this doesn't happen on the android test phone for some reason).  Some googling suggests that linking the package will fix the issue.
> Linked icon package

- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/transaction-screen/transaction-screen.tsx
> Fix transaction history screen staleness

- __tests__/screens/__snapshots__/send-bitcoin-confirmation-screen.spec.tsx.snap
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
Confirm send bitcoin button is now at the bottom of the screen.
> Fixed confirm payment button position

- app/components/transaction-item/transaction-item.tsx
- app/graphql/graphql.types.d.ts
- app/graphql/query.ts
- app/screens/transaction-detail-screen/transaction-detail-screen.tsx
Please merge and release after this gets deployed: https://github.com/GaloyMoney/galoy/pull/759
> Implement the changes in transactions API data

- app/app.tsx
This PR fixes Universal Link functionality.
> Fix Universal Links

- __tests__/screens/__snapshots__/send-bitcoin-confirmation-screen.spec.tsx.snap
- __tests__/screens/__snapshots__/send-bitcoin-screen.spec.tsx.snap
- app/components/input-payment/input-payment.tsx
- app/components/modal-clipboard/modal-clipboard.tsx
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- app/screens/receive-bitcoin-screen/qr-view.tsx
- app/screens/send-bitcoin-screen/payment-confirmation-information.tsx
- app/screens/send-bitcoin-screen/payment-status-indicator.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
I worked with Arvin in his local environment to debug the issue with certain text not showing up for him.  It looks like certain devices don't inherit the font colours properly.  We explicitly set the text colour in certain places in the app and this fixed the problem.
> Adding explicit colors to Text

- app/components/transaction-item/transaction-item.tsx
- app/graphql/query.ts
- app/screens/transaction-detail-screen/transaction-detail-screen.tsx
> Fix onchain tx hash

- app/components/modal-clipboard/modal-clipboard.tsx
- app/components/onboarding/onboarding.tsx
- app/components/version/version.tsx
- app/hooks/use-money-amount.ts
- app/navigation/stack-param-lists.ts
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx
- app/utils/clipboard.ts
Adds some types to take care of the check code complaints.
> Replace anies with types

- app/hooks/use-geetest-captcha.ts
- ios/Podfile.lock
- package.json
- yarn.lock
> Upgrade geetest module.

- app/i18n/en.json
- app/i18n/es.json
Just fixing some minor grammar on the onboarding flow. Let's make our best impression!
This was contributed to us by @FuzzWorley. Thanks to him!
> fix some minor grammar and punctuation to onboarding flow

- android/app/proguard-rules.pro
> Added horcrux svg library to proguard rules

- android/app/src/main/java/com/galoyapp/MainApplication.java
> Add null to super.onCreate() args

- app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx
> Update USD amount on invoice with sat amount.

- app/components/input-payment/input-payment.tsx
- app/i18n/en.json
- app/i18n/es.json
- app/navigation/stack-param-lists.ts
- app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-screen.tsx
- app/screens/send-bitcoin-screen/use-fee.ts
- app/utils/parsing.ts
- package.json
- yarn.lock
This PR picks up where https://github.com/GaloyMoney/galoy-mobile/pull/321 left off from @pseudozach. This PR adds support for sending sats with lnurl-pay.
> Add lnurl-pay (round 2)

- app/components/transaction-item/transaction-item.tsx
- app/i18n/es.json
> fix: Fix translations and spelling

- app/i18n/pt-br.json
File provided by motolese in #414.  There is some follow up work to expose the option to the user required in the app, but this should happen after we have made the necessary server side change to support the new language as a user preference.
> feat: add Brazil Portuguese translation

- app/screens/send-bitcoin-screen/use-fee.ts
> fix: fix fee probe error handling

- __tests__/screens/global-error.spec.tsx
- app/app.tsx
- app/components/global-error/global-error.tsx
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/settings-screen/lnurl-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/utils/toast.ts
- jest.config.js
- package.json
- yarn.lock
This PR implements a new error toast which is similar to the one proposed in the design.  It doesn't match the design exactly but it should be easy to customize in the future if we want to.
> feat: Add new toast

- package.json
- yarn.lock
> feat: Upgrade google phone validation lib

- app/components/large-button/large-button.tsx
- app/components/transaction-item/transaction-item.tsx
- app/graphql/graphql.types.d.ts
- app/graphql/query.ts
- app/hooks/hooks.types.d.ts
- app/hooks/use-main-query.ts
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/transaction-screen/transaction-screen.tsx
- app/utils/currencyConversion.ts
- use galoy-client for transactions by account
- format transaction screen
> feat: unified transaction history

- app/components/payment-destination-display/payment-destination-display.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation.tsx
- app/screens/send-bitcoin-screen/send-bitcoin.tsx
- app/screens/send-bitcoin-screen/send-bitcoin.types.ts
- add better typing
- fix username showing up twice in destination field
- fix breaking typo for setting recipientWalletId
> fix: send to username

- app/screens/earns-screen/earns-section.tsx
fixes #467 on usd-integration branch
> Show errors on quiz screens

- app/screens/send-bitcoin-screen/send-bitcoin-amount.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation.tsx
- app/screens/send-bitcoin-screen/send-bitcoin.tsx
- remove incorrect fee icon
- add note to confirmation screen
- fix spacing issues in send flow
> fix: clean up send bitcoin ui

- __tests__/screens/global-error.spec.tsx
- app/components/contact-modal/contact-modal.tsx
- app/components/contact-modal/index.ts
- app/components/global-error/global-error.tsx
- app/constants/support.ts
- app/screens/contacts-screen/contact-transactions.tsx
- app/screens/contacts-screen/contacts.tsx
- app/screens/earns-screen/earns-section.tsx
- app/screens/error-screen/error-screen.tsx
- app/screens/map-screen/map-screen.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- app/screens/settings-screen/lnurl-screen.tsx
- app/screens/settings-screen/security-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/screens/transaction-screen/transaction-screen.tsx
- app/screens/transfer-screen/transfer-confirmation-screen.tsx
- app/utils/toast.ts
- package.json
- yarn.lock
https://user-images.githubusercontent.com/3502409/175781883-c5ccf180-f26b-49b2-8123-8e205eb42193.MP4
> Add new contact modal and fix toasts

- app/screens/send-bitcoin-screen/use-fee.ts
> feat: use single fee probe

- app/components/price-graph/price-graph.tsx
- package.json
- yarn.lock
> feat: add 5Y filter to bitcoin price chart

- app/components/price-graph/price-graph.tsx
fix wrapping on buttons
add animation effects
gradient background on graph
before:
after:
> feat: improve price graph design and layout

- app/navigation/root-navigator.tsx
- app/navigation/stack-param-lists.ts
- app/screens/receive-bitcoin-screen/receive-bitcoin.tsx
- yarn.lock
- Screen title now shows "Receive USD" instead of "Receive Bitcoin" when creating a USD invoice
> feat: add receive usd screen title

- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/use-fee.ts
- yarn.lock
Fixes #554 .  https://github.com/GaloyMoney/galoy-client/pull/53 needs to be merged first before this can be merged.
> feat: enable send payment when fee probe fails

- app/hooks/user-hooks.ts
On some screens the price cache was sending down 0 because the values in the `useEffect` call were not updating in between the screen rendering and attempting to utilise the price cache in some operation.
> fix: Fixed price cache initialising with 0

- app/components/transaction-date/transaction-date.tsx
- app/utils/date.ts
I think this will fix the issues we are seeing with momentjs.  Here's a thread on the wider issue if you are interested https://github.com/moment/moment/issues/3624.  @samerbuna you might want to think about also using the util method in the web wallet.  If you give the green light I can raise the PR.
> fix: Fixed moment locale issue

- __tests__/screens/__snapshots__/phone-auth.spec.tsx.snap
- __tests__/screens/phone-auth.spec.tsx
- app/assets/icons/downarrow.svg
- app/screens/phone-auth-screen/phone-auth.tsx
I recreated a test that had problems. I extracted the same code that uses the "PhoneInput" component, to have a component with the TestID field and be able to use it in the test.
Ref https://github.com/GaloyMoney/galoy-mobile/issues/430
> fix: test to check if country picker is visible was recreated

- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- yarn.lock
- update galoy-client
- ensure validAmount is set on each send-bitcoin-confirmation render
> fix: check amount validity on each render

- .circleci/config.yml
Removed version checks from android build
> chore: Removed version checks

- app/components/transaction-item/transaction-item.tsx
- app/screens/contacts-screen/contact-transactions.tsx
- app/screens/contacts-screen/contacts-detail.tsx
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/transaction-screen/transaction-screen.tsx
- fix strange borders on move money screen on ios
- fix section headers on transactions page on ios
- clean up contacts page
> fix: fix transaction formatting issues

- app/hooks/use-main-query.ts
- app/screens/earns-map-screen/earns-map-screen.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- prevent login causing double render flow
- default to cache on main query
- fix bug with navigating to earn screen
> fix: remove rendering quirks

- __tests__/screens/global-error.spec.tsx
- app/app.tsx
- app/hooks/use-logout.ts
- app/navigation/root-navigator.tsx
- app/screens/authentication-screen/authentication-check-screen.tsx
- app/screens/authentication-screen/authentication-screen.tsx
- app/screens/authentication-screen/pin-screen.tsx
- app/store/authentication-context.tsx
- fixes security issue as discussed internally
> fix: prevent lock bypass

- __tests__/screens/global-error.spec.tsx
- app/app.tsx
- app/store/authentication-context.tsx
- fix deeplinking
- enable linking after unlock
> fix: deeplinking

- app/hooks/use-amount.ts
- app/screens/conversion-flow/conversion-details-screen.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- prevent negative amounts in useUsdBtcAmount hook
- use useUsdBtcAmount hook in send bitcoin flow
> fix: prevent negative amounts

- app/components/balance-header/balance-header.tsx
- app/hooks/use-main-query.ts
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/price-screen/price-screen.tsx
- show balance loading animation when refetching
- correct loading animation shape
- rewrite balance header for simplicity
> fix: fix balance header loading

- app/navigation/root-navigator.tsx
- app/screens/conversion-flow/conversion-confirmation-screen.tsx
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/utils/analytics.ts
- firebase.json
- ios/GaloyApp.xcodeproj/xcshareddata/xcschemes/GaloyApp.xcscheme
- ios/GoogleService-Info.plist
- add analytics events so we can answer questions posed in issue #597
> feat: add analytics events

- app/i18n/en/index.ts
- app/i18n/es/index.ts
- app/i18n/fr-CA/index.ts
- app/i18n/i18n-types.ts
- app/i18n/pt-BR/index.ts
- app/screens/settings-screen/settings-screen.tsx
Apple app store requires us to have an account deletion method in the app.
> fix: Added account deletion button

- app/screens/receive-bitcoin-screen/receive-bitcoin.tsx
- package.json
- yarn.lock
I'm upgrading the client to a new version which parses signet invoices.
> Fix signet invoice parsing

- app/components/modal-clipboard/modal-clipboard.tsx
- app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/utils/clipboard.ts
- use updated galoy client to enable fallback url in lnurl
- switch to using parsingv2 across app
> chore: update galoy client

- app/screens/receive-bitcoin-screen/qr-view.tsx
This PR fixes this issue https://github.com/GaloyMoney/galoy-mobile/issues/679
> fix: zoomed QR size on large screens on android

- app/screens/receive-bitcoin-screen/receive-usd.tsx
- package.json
- yarn.lock
- allows taproot addresses
- fixes issue with signet usd invoices
> chore: upgrade galoy client to 0.1.60

- transifex.yml
- add transifex integration config
> chore: update transifex config

- .circleci/config.yml
- app/components/contact-modal/contact-modal.tsx
- app/components/global-error/global-error.tsx
- app/hooks/use-logout.ts
- app/navigation/root-navigator.tsx
- app/navigation/stack-param-lists.ts
- app/screens/contacts-screen/contacts.tsx
- app/screens/conversion-flow/conversion-confirmation-screen.tsx
- app/screens/earns-screen/earns-utils.ts
- app/screens/map-screen/map-screen.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- app/screens/send-bitcoin-screen/use-fee.ts
- app/screens/settings-screen/settings-screen.tsx
- app/store/price-context.tsx
- app/utils/biometricAuthentication.ts
- app/utils/notifications.ts
- symbolicate-trace.sh
- record caught errors with crashlytics
- add script to symbolicate crashlytics trace
- prevent updating state during render for globar-error component
- rename contacts screen to prevent nested naming
> chore: improve error handling

- android/app/build.gradle
should have a 4x reduction in size
before:
```
94517161 Dec 28 19:47 app-release.apk
371 Dec 28 19:47 output-metadata.json
```
after:
```
35483879 Dec 28 20:50 app-arm64-v8a-release.apk
29686619 Dec 28 20:50 app-armeabi-v7a-release.apk
36350363 Dec 28 20:50 app-x86-release.apk
37515601 Dec 28 20:50 app-x86_64-release.apk
1320 Dec 28 20:50 output-metadata.json
> chore: make app smaller to install, step 1

- app/components/atomic/galoy-button-field/galoy-button-field.story.tsx
- app/components/atomic/galoy-button-field/galoy-button-field.tsx
- app/components/atomic/galoy-button-field/index.ts
- app/components/atomic/galoy-currency-bubble/galoy-currency-bubble.story.tsx
- app/components/atomic/galoy-currency-bubble/galoy-currency-bubble.tsx
- app/components/atomic/galoy-currency-bubble/index.ts
- app/components/atomic/galoy-icon-button/galoy-icon-button.story.tsx
- app/components/atomic/galoy-icon-button/galoy-icon-button.tsx
- app/components/atomic/galoy-icon-button/index.ts
- app/components/atomic/galoy-icon/galoy-icon.story.tsx
- app/components/atomic/galoy-icon/galoy-icon.tsx
- app/components/atomic/galoy-primary-button/galoy-primary-button.story.tsx
- app/components/atomic/galoy-primary-button/galoy-primary-button.tsx
- app/components/atomic/galoy-secondary-button/galoy-secondary-button.story.tsx
- app/components/atomic/galoy-secondary-button/galoy-secondary-button.tsx
- app/rne-theme/colors.ts
- app/rne-theme/theme.ts
- app/rne-theme/themed.d.ts
- app/screens/settings-screen/transaction-limits-screen.tsx
- jest.config.js
- package.json
- storybook/defaults/colors.story.tsx
- storybook/defaults/text.story.tsx
- storybook/storybook-registry.ts
- add GaloyIconButton
- add GaloyCurrencyBubble
- add GaloyButtonField
- set up typography theming
- create theme default stories
> feat: create more components

- ios/Podfile
this will make the app launch much faster on iOS
> feat: activate hermes on ios

- app/components/atomic/galoy-button-field/galoy-button-field.tsx
- app/components/atomic/galoy-icon/galoy-icon.tsx
- app/components/atomic/galoy-primary-button/galoy-primary-button.tsx
- app/components/atomic/galoy-secondary-button/galoy-secondary-button.tsx
- use makeStyles in atomic components
> chore: refactor to use makeStyles

- ios/GaloyApp.xcodeproj/project.pbxproj
- ios/Podfile
- ios/Podfile.lock
spent a good part of the day onto this. I think it's worth looking more into it once v0.71 has been released as there are many moving part for this one.
> chore: give up on hermes on ios for now

- app/hooks/use-countdown-timer.ts
- app/screens/map-screen/map-screen.tsx
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- app/screens/send-bitcoin-screen/use-fee.ts
- app/store/localization-context.tsx
- app/utils/date.ts
-  fixes repeated logging out with expired session token
- evaluates the use of disable linting rules and reenables them where neccessary
> fix: add missing useEffect dependencies

- app/navigation/root-navigator.tsx
- app/screens/galoy-address-screen/set-address-modal.tsx
This should fix and close this issue https://github.com/GaloyMoney/galoy-mobile/issues/799
> fix: fix username suffix based on app env

- ci/pipeline.yml
> ci: fix time resource

- .circleci/config.yml
Reverts GaloyMoney/galoy-mobile#823
> Revert "chore: do test_ios on every build, including in PR"

- .circleci/config.yml
FYI I've changed some settings in circleci.
> Test and prs workflows

- app/store/localization-context.tsx
- prevent infinite rerenders when alternative language is set
> fix: alternative languages

- e2e/01-welcome-screen-flow.e2e.spec.ts
- e2e/02-login-flow.e2e.spec.ts
- e2e/03-payments-flow.e2e.spec.ts
- e2e/04-payments-receive-flow.e2e.spec.ts
- e2e/utils/selector.ts
I feel this doesn't really help on the learning curve.
The selector will very often not be Button (more than 50% of the time). not putting an explicit "Button" for now. will refactor more as tests expand.
> chore: not assume Button as default for ElementType

- __tests__/screens/global-error.spec.tsx
- app/app.tsx
- app/components/galoy-toast/galoy-toast.tsx
- app/components/galoy-toast/index.ts
- app/components/global-error/global-error.tsx
- app/hooks/use-logout.ts
- app/screens/contacts-screen/contact-transactions.tsx
- app/screens/debug-screen/debug-screen.tsx
- app/screens/galoy-address-screen/galoy-address-screen.tsx
- app/screens/galoy-address-screen/merchants-dropdown.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/screens/settings-screen/lnurl-screen.tsx
- app/screens/settings-screen/security-screen.tsx
- app/screens/transaction-screen/transaction-screen.tsx
- app/utils/analytics.ts
- app/utils/toast.ts
- enable custom toast components through GaloyToast
- log toast events
> chore: refactor toast component

- app/graphql/generated.ts
- app/graphql/operation/queries.ts
- docs/e2e-testing.md
- e2e/01-welcome-screen-flow.e2e.spec.ts
- e2e/04-payments-receive-flow.e2e.spec.ts
- e2e/06-change-language.e2e.spec.ts
- e2e/utils/graphql.ts
because of the optimisic mutation (?), it seems there is a race condition where we click on predefined before the previous mutation has been back from the server.
a short pausing should mitigate the issue
> chore: fix language test?

- app/screens/send-bitcoin-screen/use-fee.ts
> fix: crash on checking fees for lightning

- app/screens/authentication-screen/authentication-check-screen.tsx
there is no reason AuthenticationCheckScreen need to rely on any of those values?
> chore: AuthenticationCheckScreen refactor

- .eslintrc.json
- app/app.tsx
- app/graphql/cache.ts
- app/graphql/generated.ts
- app/graphql/operations/local/schema.graphql
- app/graphql/operations/remote/queries.ts
- app/navigation/root-navigator.tsx
- app/navigation/stack-param-lists.ts
- app/screens/conversion-flow/conversion-confirmation-screen.tsx
- app/screens/conversion-flow/conversion-details-screen.tsx
also removing some duplicated states
> chore: removing dependance on mainQuery from conversion screen

- app/config/galoy-instances.ts
- app/screens/contacts-screen/contact-transactions.tsx
- app/screens/galoy-address-screen/address-explainer-modal.tsx
- app/screens/galoy-address-screen/galoy-address-screen.tsx
- app/screens/galoy-address-screen/set-address-modal.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/screens/transaction-screen/transaction-screen.tsx
eventually I think this value can come from globals?
> chore: refactor bank name

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/graphql/operations/remote/fragments.ts
- app/hooks/use-geetest-captcha.ts
- app/screens/earns-screen/earns-section.tsx
- app/screens/galoy-address-screen/set-default-wallet.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/settings-screen/language-screen.tsx
it's automatically been added by codegen
> chore: removing __typename

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/graphql/utils.ts
- app/navigation/stack-param-lists.ts
- app/screens/earns-map-screen/earns-map-screen.tsx
- app/screens/earns-screen/earns-quiz.tsx
- app/screens/earns-screen/earns-section.tsx
- app/screens/earns-screen/earns-utils.ts
- app/utils/toast.ts
- codegen.yml
- package.json
needs: https://github.com/GaloyMoney/galoy/pull/2175 to be merged first
> chore: another refactoring iteration on earn

- app/screens/receive-bitcoin-screen/qr-view.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- app/screens/send-bitcoin-screen/use-fee.ts
- tsconfig.json
- enables strict null checks
- disables ts checking on send flow files that are being refactored
> chore: enable strict null checks

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/screens/authentication-screen/authentication-check-screen.tsx
- app/screens/conversion-flow/conversion-confirmation-screen.tsx
- app/screens/conversion-flow/conversion-success-screen.tsx
- app/screens/earns-screen/earns-quiz.story.tsx
- app/screens/galoy-address-screen/set-address-modal.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-success-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
also: do the refetch transaction where the query happens, instead of another screen (payment confirmation)
> chore: removing unnecessary client import

- app/graphql/client.tsx
it's unclear if/why we need to store the persistor in a state. so remove it for now.
> chore: iteration on apollo client

- app/graphql/cache.ts
- app/graphql/client.tsx
- app/graphql/generated.gql
- app/graphql/generated.ts
- remove price cache
- update root query cache on price from subscription
> chore: fix price changing bug

- .typesafe-i18n.json
- app/app.tsx
- app/graphql/cache.ts
- app/graphql/client.tsx
- app/hooks/use-logout.ts
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/settings-screen/language-screen.tsx
- app/store/localization-context.tsx
extracting the refactoring part of this PR: https://github.com/GaloyMoney/galoy-mobile/pull/938
will rebase https://github.com/GaloyMoney/galoy-mobile/pull/938 afterwards so that the more "risky" part of the diff are remaining.
> chore: reorg import of appolo network layer

- __tests__/screens/global-error.spec.tsx
- app/app.tsx
- app/graphql/analytics.tsx
- app/graphql/client.tsx
- app/graphql/generated.gql
- app/graphql/generated.ts
- app/graphql/is-authed-context.ts
- app/navigation/root-navigator.tsx
- app/screens/authentication-screen/authentication-check-screen.tsx
- app/screens/contacts-screen/contacts.tsx
- app/screens/earns-map-screen/earns-map-screen.tsx
- app/screens/earns-screen/earns-section.tsx
- app/screens/map-screen/map-screen.tsx
- app/screens/move-money-screen/move-money-screen.tsx
- app/screens/phone-auth-screen/phone-auth.tsx
- app/screens/receive-bitcoin-screen/receive-bitcoin.tsx
- app/screens/settings-screen/account-screen.tsx
- app/screens/settings-screen/language-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/store/authentication-context.tsx
@UncleSamtoshi let me know what you think about this approach. there is still one hasToken remaining but I need to refactor `<App />` before i can remove it. 
but it seems to remove the current issue of reload without a token for now.
> chore: isAuthed attached to the client lifecycle

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/screens/move-money-screen/move-money-screen.tsx
this allow for caching for the unauthed query.
this is a best practive recommended by Apollo Client: https://www.apollographql.com/docs/react/data/operation-best-practices#query-global-data-and-user-specific-data-separately
> chore: only fetch full me query is authed

- __tests__/utils/locale-detector.test.ts
- app/app.tsx
- app/graphql/client.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/i18n-util.async.ts
- app/i18n/i18n-util.sync.ts
- app/i18n/i18n-util.ts
- app/i18n/raw-i18n/source/en.json
- app/i18n/th/index.ts
- app/screens/settings-screen/language-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/utils/locale-detector.ts
- add thai language support
- improve typing around languages
- fix bug with setting languages
> chore: refactor setting languages

- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- e2e/04-username-payments-flow.e2e.spec.ts
Reverts GaloyMoney/galoy-mobile#997
> Revert "fix: Fixed issue with btc wallet balance"

- app/graphql/transactions.ts
- app/screens/contacts-screen/contact-transactions.tsx
- app/screens/transaction-screen/transaction-screen.tsx
- cleaner code
- this may help to have smoother transaction screen on old device (?)
> chore: memoizing transaction parsing

- .eslintrc.json
- app/navigation/navigation-container-wrapper.tsx
- app/navigation/root-navigator.tsx
- app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/store/persistent-state/index.tsx
- app/utils/biometricAuthentication.ts
going to use `await` only make the code easier to understand (for me at least) and more importantly more consistent.
there is still one `then` left but I'll tackle it in another PR
> chore: removing some then() pattern with async/await

- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- ios/Podfile.lock
Currently if you try to pay yourself using your username in the app, you get a toast UI with the message `Error checking username`. We instead want to show the user the message telling them they can't pay themselves. This PR fixes that.
> chore: refactor check for self intraledger payment

- app/screens/conversion-flow/conversion-success-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-success-screen.tsx
I think time also include the transaction
putting 3 seconds instead to try it out
> chore: 2s is short for a confirmation page.

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/screens/settings-screen/settings-screen.tsx
> fix: get transaction with CSV format

- app/screens/home-screen/home-screen.tsx
misunderstood the use of useCallback
fix #1072
> fix: refresh in home

- e2e/02-login-flow.e2e.spec.ts
- e2e/utils/graphql.ts
- currently we grab a random token every time we are trying to grab the same token
- this pr chooses a single random token and uses that for the remainder of the test
> fix: inconsistent e2e token

- app/graphql/client.tsx
- app/graphql/generated.ts
- app/graphql/ln-update-context.ts
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
> chore: only subscribe to myUpdates once

- app/screens/earns-screen/earns-quiz.tsx
> chore: remove redundant state

- index.js
- ignores navigation serialization and deserialization warning for sendbitcoin flow
> chore: add logbox igore for known cases

- __tests__/payment-destination/lnurl.spec.ts
- __tests__/payment-destination/onchain.spec.ts
- app/screens/send-bitcoin-screen/payment-destination/lnurl.ts
- app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- ios/Podfile.lock
> fix: lnurl parsing

- __tests__/payment-destination/lnurl.spec.ts
> chore: add lnurl tests

- app/screens/redeem-lnurl-withdrawal-screen/redeem-bitcoin-detail-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- e2e/03-intraledger-flow.e2e.spec.ts
- e2e/04-payment-send-flow.e2e.spec.ts
- ios/Podfile.lock
first draft of lnurlp e2e test. 
temporarily using external addres but will remove after draft is complete.
> chore: add e2e test for lnurl pay and knurl withdraw

- app/screens/galoy-address-screen/merchants-dropdown.tsx
- app/screens/galoy-address-screen/set-default-wallet.tsx
Issue doesn't show in prod but in dev.
> fix: UI error on merchant dropdown in galoy address screen

- .storybook/views/story-screen.tsx
- .storybook_server/main.js
- app/components/contact-modal/contact-modal.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/earns-map-screen/earns-map-screen.stories.tsx
- app/screens/home-screen/home-screen.stories.tsx
- app/screens/phone-auth-screen/phone-flow.stories.tsx
- app/screens/phone-auth-screen/phone-validation.stories.tsx
- app/screens/settings-screen/settings-screen.stories.tsx
- app/screens/settings-screen/settings-screen.tsx
- fix #1160
- some stories improvments
> feat: add mobile version and os to support message request

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/screens/earns-map-screen/earns-map-screen.tsx
- app/screens/earns-map-screen/use-quiz-server.tsx
- app/screens/earns-screen/earns-quiz.tsx
- app/screens/earns-screen/earns-section.tsx
- app/screens/earns-screen/earns-utils.ts
> chore: fix 0 sats in earn when not logged in

- app/screens/settings-screen/settings-screen.tsx
> feat: Improved address display in settings screen

- app/screens/galoy-address-screen/galoy-address-screen.tsx
- app/screens/settings-screen/transaction-limits-screen.tsx
it's an important feature to contribute to the liveness of the mobile app
> chore: make screen scrollable

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
it's unused, but also appears in the translation for transifex as many times as we have questions currently
> chore: remove type: Text

- .circleci/config.yml
- ci/pipeline.yml
- ci/tasks/choose-commit-prerelease.sh
- ci/tasks/upload-to-app-store.sh
- choose commit script fix
- upload to app store via circleci
> ci: upload to app store via circleci

- .circleci/config.yml
- __tests__/payment-details/helpers.ts
- app/components/money-amount-input/index.tsx
- app/components/transaction-item/transaction-item.tsx
- app/hooks/use-display-currency.ts
- app/screens/conversion-flow/conversion-confirmation-screen.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- app/screens/send-bitcoin-screen/payment-destination/index.types.ts
- app/screens/send-bitcoin-screen/payment-details/index.types.ts
- app/screens/send-bitcoin-screen/payment-details/intraledger.ts
- app/screens/send-bitcoin-screen/payment-details/lightning.ts
- app/screens/send-bitcoin-screen/payment-details/onchain.ts
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- app/screens/settings-screen/transaction-limits-screen.tsx
- app/screens/transaction-detail-screen/transaction-detail-screen.tsx
- e2e/03-intraledger-flow.e2e.spec.ts
- e2e/04-payment-send-flow.e2e.spec.ts
- create MoneyAmountInput component
- modify PaymentDetails types to handle WalletOrDisplayCurrency
- update send flow to use display currency
> feat: enable send flow display currency

- app/screens/conversion-flow/conversion-details-screen.tsx
fixes issue https://github.com/GaloyMoney/galoy-mobile/issues/1305
> fix: conversion amount field error

- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
fixes issue https://github.com/GaloyMoney/galoy-mobile/issues/1304
> fix: error crash for USD wallet onchain payment

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/navigation/stack-param-lists.ts
- app/screens/redeem-lnurl-withdrawal-screen/redeem-bitcoin-detail-screen.tsx
- app/screens/redeem-lnurl-withdrawal-screen/redeem-bitcoin-result-screen.tsx
- added in display currency
- deleted unused code for usd wallet use case as usd wallet is not supported until we can denominate usd invoices in sats
> feat: display currency in lnurlw

- app/components/balance-header/balance-header.tsx
- app/components/wallet-overview/wallet-overview.tsx
- app/graphql/cache.ts
- app/screens/home-screen/home-screen.tsx
- we should not rely on DisplayCurrencyQuery anymore because this data may be flushed on app update
- also adding some Loader to avoid flickering on the Wallet Overview component
> chore: proper fix for NaN when updating version

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/screens/home-screen/home-screen.tsx
new PR to attempt fixing the NaN on version update. 
It's more tricky than what I thought to get the cache right when we have screen that embedded component that themselves rely on cache. 
right now trying to fix the build, but this may me think whether our approach is the ideal one.
> chore: new attempt at fixing bug for NaN on version update

- __tests__/payment-destination/lnurl.spec.ts
- app/screens/receive-bitcoin-screen/use-payment-request.ts
- app/screens/redeem-lnurl-withdrawal-screen/redeem-bitcoin-result-screen.tsx
- app/screens/send-bitcoin-screen/payment-destination/index.types.ts
- app/screens/send-bitcoin-screen/payment-destination/lnurl.ts
- app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/utils/analytics.ts
- ios/Podfile.lock
- add back in parse destination events
- add back in generate payment request events
> fix: regressions in analytics events

- app/components/money-amount-input/index.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- show display amount instead of btc amount for fixed amount invoices
- prevent minor field from being editable
> fix: display amounts in fixed amount invoices

- android/fastlane/Fastfile
- ci/image/fastlane-image/Dockerfile
- ci/image/pipeline-image/Dockerfile
- ci/pipeline.yml
- ci/tasks/build-on-circleci.sh
- ci/tasks/bump-and-commit-build-number.sh
- ci/tasks/bump-beta-to-public-pr.sh
- ci/tasks/bump-testflight-to-beta-pr.sh
- ci/tasks/choose-commit-prerelease.sh
- ci/tasks/e2e-test-android.sh
- ci/tasks/e2e-test-ios.sh
- ci/tasks/helpers.sh
- ci/tasks/migrate-existing-beta-prs.sh
- ci/tasks/migrate-existing-public-prs.sh
- ci/tasks/prep-prelease-src.sh
- ci/tasks/promote-app-store.sh
- ci/tasks/promote-play-store.sh
- ci/tasks/release.sh
- ci/tasks/upload-to-app-store.sh
- ci/templates/deployments-pr-body.md
- ci/values.yml
- ios/fastlane/Fastfile
- making repo passed
- making sure apk and ipa in sync at prerelease
- separation of versions
> ci: improvements

- app/screens/conversion-flow/conversion-confirmation-screen.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
> feat: Added haptic feedback for receive and send screen

- __tests__/payment-details/lnurl-payment-details.spec.ts
- app/screens/send-bitcoin-screen/payment-details/lightning.ts
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
addresses issue https://github.com/GaloyMoney/galoy-mobile/issues/1435
> chore: support LNURL payRequest with predefined amount

- app/components/atomic/galoy-tertiary-button/galoy-tertiary-button.stories.tsx
- app/components/atomic/galoy-tertiary-button/galoy-tertiary-button.tsx
- app/components/contact-support-button/contact-support-button.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/phone-auth-screen/phone-input.tsx
- app/utils/toast.ts
- extend duration to dismiss toast errors
- add contact support button to phone flow
> chore: improve phone errors

- app/screens/home-screen/home-screen.tsx
- fixes issue where balances are `NaN` on home screen if any error is returned from gql
> chore: add partial results to home screen

- app/screens/receive-bitcoin-screen/receive-btc.tsx
Fixes for #622
**Preview**
https://user-images.githubusercontent.com/74586135/228163058-40e8ba80-c7a6-4c8c-8653-0b9d638db1d6.mp4
> Fix: Receive screen copy msg fixed

- ci/tasks/phased-rollout.sh
- ci/tasks/prerelease.sh
> ci: fix scripts

- .storybook/storybook.requires.js
- app/components/amount-input/amount-input-button.tsx
- app/components/amount-input/amount-input-modal.tsx
- app/components/amount-input/amount-input.stories.tsx
- app/components/amount-input/amount-input.tsx
- app/components/amount-input/index.ts
- app/components/money-amount-input-modal/index.ts
- app/screens/conversion-flow/conversion-details-screen.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- e2e/03-intraledger-flow.e2e.spec.ts
- e2e/04-payment-send-flow.e2e.spec.ts
- e2e/05-payments-receive-flow.e2e.spec.ts
- e2e/utils/numberpad.ts
- renames the MoneyAmountInputModal to AmountInput
- adds AmountInput to receive flow and conversion flow
> feat: use new amount input component

- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- ensures that for fixed amount invoices, the btc amount is not converted
> fix: correct amount in amount input

- e2e/config/browserstack.conf.js
- e2e/config/wdio.conf.js
- logs network traffic in e2e tests
- ends the test run if a single test fails
> test: improve e2e config

- app/components/amount-input-screen/amount-input-screen.tsx
- app/navigation/stack-param-lists.ts
- app/screens/redeem-lnurl-withdrawal-screen/redeem-bitcoin-detail-screen.tsx
- app/screens/redeem-lnurl-withdrawal-screen/redeem-bitcoin-result-screen.tsx
- use amount input in redeem btc screen
- switch minAmount and maxAmount parameters to not be converted
> feat: use input in redeem screen

- app/components/wallet-summary/wallet-summary.tsx
- app/hooks/use-display-currency.ts
> chore: add display currency in transaction details

- ci/pipeline.yml
> ci(revert): passed repo for bump testflight

- app/components/amount-input-screen/amount-input-screen-ui.tsx
- app/components/amount-input/amount-input-button.tsx
- app/components/amount-input/amount-input.stories.tsx
- app/components/amount-input/amount-input.tsx
- app/rne-theme/theme.ts
- app/screens/conversion-flow/conversion-details-screen.tsx
- app/screens/redeem-lnurl-withdrawal-screen/redeem-bitcoin-detail-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- ios/Podfile.lock
- prevents text cut off with primary button and amount input
- show display currency first in amount input
> fix: formatting issues with large text

- app/components/price-history/price-history.tsx
- app/navigation/root-navigator.tsx
- app/rne-theme/colors.ts
- app/screens/settings-screen/settings-row.tsx
> chore: some design improvement

- app/screens/settings-screen/display-currency-screen.tsx
> fix: currency list to reset correctly when tapping x

- .storybook/storybook.requires.js
- .storybook/storybook.tsx
- app/components/atomic/galoy-button-field/galoy-button-field.stories.tsx
- app/components/atomic/galoy-button-field/galoy-button-field.tsx
- app/components/atomic/galoy-primary-button/galoy-primary-button.tsx
- app/components/screen/screen.presets.ts
- app/components/screen/screen.props.ts
- app/components/screen/screen.tsx
- app/components/stablesats-modal/stablesats-modal.tsx
- app/rne-theme/theme.stories.tsx
- app/screens/conversion-flow/conversion-details-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- app/screens/transaction-history/transaction-history-screen.tsx
- handle larger fonts in conversion flow
- handle larger fonts in atomic components
- clean up send flow styling
> chore: various ui improvements

- ci/config/git-cliff-release.toml
- ci/tasks/bump-beta-to-public-pr.sh
- ci/tasks/bump-testflight-to-beta-pr.sh
- ci/tasks/migrate-existing-beta-prs.sh
- ci/tasks/migrate-existing-public-prs.sh
@nicolasburtey as you requested 😎
ex:
> ci: public release body have author details and only features and fixes

- app/components/atomic/galoy-currency-bubble/galoy-currency-bubble.stories.tsx
- app/components/atomic/galoy-icon-button/galoy-icon-button.stories.tsx
- app/components/atomic/galoy-icon/galoy-icon.stories.tsx
- app/components/atomic/galoy-input/galoy-input.stories.tsx
- app/components/atomic/galoy-primary-button/galoy-primary-button.stories.tsx
- app/components/atomic/galoy-secondary-button/galoy-secondary-button.stories.tsx
- app/components/atomic/galoy-tertiary-button/galoy-tertiary-button.stories.tsx
- app/components/currency-keyboard/currency-keyboard.stories.tsx
- app/screens/contacts-screen/contacts-detail.stories.tsx
- tested all the storybooks visually to find no differences
> chore: upgrade storybook syntaxes to csf3

- ios/Podfile.lock
- package.json
- yarn.lock
some surprises:
- libphonenumber.js is 500kb+ (dependancy of our phone input library)
- some SVG are 250kb+. we should probably compress them somehow
> chore: adding bundle visualizer

- app/components/contact-modal/contact-modal.tsx
- app/components/contact-support-button/contact-support-button.tsx
- app/components/new-name-blink-modal/new-name-blink-modal.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/error-screen/error-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/screens/settings-screen/transaction-limits-screen.tsx
- adds contact modal for limits upgrade
- contact-modal component is now reusable
- fix dark mode for contact modal
- fix with of blink modal
- fix skewed texts in tx limits screen for large font displays
> chore: add contact modal for limits upgrade

- ci/config/git-cliff-release.toml
- ci/tasks/bump-beta-to-public-pr.sh
- ci/tasks/bump-testflight-to-beta-pr.sh
- ci/tasks/migrate-existing-beta-prs.sh
- ci/tasks/migrate-existing-public-prs.sh
- Have only Features and Bug Fixes.
- Show author of PRs.
> ci: have username in release notes

- .storybook/views/story-screen.tsx
- app/app.tsx
- app/config/feature-flags-context.tsx
- app/graphql/client.tsx
- app/graphql/feature-flags-context.tsx
- app/graphql/generated.gql
- app/graphql/generated.ts
- app/graphql/level-component.tsx
- app/graphql/level-context.ts
- app/hooks/use-app-config.ts
- app/navigation/stack-param-lists.ts
- app/screens/earns-screen/earns-section.tsx
- app/screens/get-started-screen/get-started-screen.stories.tsx
- app/screens/get-started-screen/get-started-screen.tsx
- app/screens/get-started-screen/lite-account.stories.tsx
- app/screens/get-started-screen/lite-account.tsx
- app/screens/get-started-screen/use-device-token.ts
- app/screens/phone-auth-screen/phone-validation.tsx
- app/screens/settings-screen/account-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/store/persistent-state/state-migrations.ts
- codegen.yml
- ios/Podfile.lock
- package.json
- yarn.lock
- add feature flag
- clean up level naming
- use new device account mutation
> Feat  device account 2

- ios/Podfile.lock
- package.json
- yarn.lock
fix some perfomances issue and other misc.
> chore: upgrade to react 0.71.8

- app/graphql/level-component.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/send-bitcoin-screen/send-bitcoin-details-extra-info.tsx
- app/screens/settings-screen/transaction-limits-screen.tsx
- update limits copy
- fix account level provider
> chore: update limits copy

- .storybook/storybook.requires.js
- .storybook/storybook.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/galoy-address-screen/address-explainer-modal.tsx
- app/screens/galoy-address-screen/paycode-explainer-modal.tsx
- app/screens/galoy-address-screen/pos-explainer-modal.tsx
using "react-native-modal" package consistently
also improving the wording on a few boards
> chore: not using react-native/modal anymore

- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
> fix: changed color of note input field in receive screen in dark mode

- app/components/payment-destination-display/payment-destination-display.tsx
Fixes issue #2206 
**Preview**
> fix: fixed cropped destination field in send payment flow

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/rne-theme/theme.ts
- app/screens/home-screen/home-screen.tsx
- app/screens/phone-auth-screen/phone-input.tsx
- app/screens/phone-auth-screen/phone-validation.tsx
- app/screens/phone-auth-screen/useRequestPhoneCode.ts
- enable pasting phone number and phone code
- disable certain countries
- auto focus country input
> chore: phone flow feedback

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
Andrew's comment: https://chat.galoy.io/galoy/pl/5wttxawtf3fmpjgmhhpcbejh9r
> chore: smaller text in default account screen

- ci/pipeline.yml
- ci/tasks/choose-commit-prerelease.sh
- ci/tasks/e2e-test-ios.sh
> ci: fix naming for Blink

- app/components/atomic/galoy-info/galoy-info.tsx
- app/rne-theme/colors.ts
- app/rne-theme/themed.d.ts
- app/screens/settings-screen/default-wallet.tsx
<table>
<tr>
<td>Dark Mode </td>
<td> Light Mode </td>
</tr>
<tr>
<td><image src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/776d416e-046b-4e74-8cc0-005b8b94880d" /></td>
<td><image src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/86cb8c4c-c533-4bde-ac29-68d615536d0f" /></td>
</tr>
</table>
> fix: galoy-info component colors

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
Needs to be rebased once #2310 has been merged to make check-code pass.
> style: remove extra whitespace from contact us button

- app/graphql/client.tsx
diff taken from https://github.com/GaloyMoney/galoy-mobile/pull/2318/files
> fix: device account subscription

- codegen.yml
Since device account was merged
> chore: use graphql schema from main branch on galoy

- app/screens/send-bitcoin-screen/payment-details/onchain.ts
> fix: set memo for onchain payments

- app/graphql/client.tsx
- app/hooks/use-display-currency.ts
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/phone-auth-screen/phone-validation.tsx
- app/screens/settings-screen/account-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- e2e/02-login-flow.e2e.spec.ts
- e2e/06-other-tests.e2e.spec.ts
- hide phone number
- make upgrade and log in process clearer
> chore: clean up account settings screen

- app/components/custom-modal/custom-modal.tsx
- app/screens/phone-auth-screen/phone-validation.tsx
- app/screens/settings-screen/account-screen.tsx
- e2e/02-login-flow.e2e.spec.ts
- e2e/06-other-tests.e2e.spec.ts
- don't show "Try WhatsApp" when "PhoneAccountAlreadyExist" error happens
- fix modal flickering
- make modal text black
- upgrade phone setting icon
- group enabled settings on "Account Settings" screen
> chore: address device account feedback

- app/screens/receive-bitcoin-screen/payment-requests/helpers.ts
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
- e2e/05-payments-receive-flow.e2e.spec.ts
- set default note to be "Pay to Blink Wallet user"
> chore: default invoice memo

- app/screens/send-bitcoin-screen/payment-details/onchain.ts
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
Now it will show fees for max payouts
> feat: display fees for max payout

- app/screens/galoy-address-screen/address-component.tsx
> fix: added text-shrink to avoid merging

- .storybook/storybook.requires.js
- app/components/atomic/galoy-currency-bubble/galoy-currency-bubble.tsx
- app/components/custom-modal/custom-modal.stories.tsx
- app/components/custom-modal/custom-modal.tsx
- app/components/set-default-account-modal/index.ts
- app/components/set-default-account-modal/set-default-account-modal.stories.tsx
- app/components/set-default-account-modal/set-default-account-modal.tsx
- app/graphql/cache.ts
- app/graphql/client-only-query.ts
- app/graphql/generated.gql
- app/graphql/generated.ts
- app/graphql/local-schema.gql
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/home-screen/home-screen.tsx
- prompt the user to set their default wallet on the second time they go to the receive screen
> feat: set default account on second receive

- ci/image/Dockerfile
Just adds shasum for verifying installed stuff in docker pipeline
> ci: add shasum

- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
Fixes https://github.com/GaloyMoney/galoy-mobile/issues/2449
> fix: flicker for send max button

- app/components/transaction-item/transaction-item.tsx
- app/screens/transaction-detail-screen/transaction-detail-screen.tsx
> chore: translating to/from tx

- app/components/amount-input/amount-input.tsx
- app/components/app-update/app-update.tsx
- app/screens/receive-bitcoin-screen/receive-btc.tsx
- app/screens/receive-bitcoin-screen/receive-usd.tsx
> fix: fixed jitter in modal

- __tests__/payment-request/payment-request.spec.ts
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/receive-bitcoin-screen/payment/payment-request.ts
- app/screens/receive-bitcoin-screen/receive-screen.tsx
- app/screens/receive-bitcoin-screen/use-receive-bitcoin.ts
> chore: receive screen improvements

- app/components/button-group/button-group.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/receive-bitcoin-screen/use-receive-bitcoin.ts
fixes padding and stuff:
buttons should be smame height and border radius as other fields. (Tap to set amount is correct)
buttons should have 10px between them and 0px on the sides
inactive fields should be much more obvious.
BTC icon and lightning bolt icon should be the same as in rest of app
> refactor: receive screen design improvements

- app/graphql/cache.ts
- codegen.yml
> fix: transaction on mobile

- app/components/introducing-circles-modal/introducing-circles-modal.tsx
- app/components/invite-modal/invite-modal.tsx
- app/graphql/mocks.ts
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/navigation/root-navigator.tsx
- app/screens/people-screen/circles/circles-card.tsx
- app/screens/people-screen/circles/circles-dashboard-screen.tsx
- app/screens/people-screen/circles/invite-friends-card.tsx
- app/screens/people-screen/circles/share-circles-image.tsx
- app/screens/people-screen/contacts/contacts-card.tsx
hey @sandipndev,
Feel free to take over this PR and merge into your branch https://github.com/GaloyMoney/galoy-mobile/pull/2547 if it looks good.
> chore: circles translations

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/screens/developer-screen/debug-screen.tsx
- ios/Podfile.lock
- package.json
- yarn.lock
It's not passing `./gradlew assembleRelease`
Reverts GaloyMoney/galoy-mobile#2572
> revert: chore: adding in app browser in debug screen

- app/components/september-challenge/card.tsx
- app/graphql/cache.ts
- app/graphql/client-only-query.ts
- app/graphql/generated.gql
- app/graphql/generated.ts
- app/graphql/local-schema.gql
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/navigation/root-navigator.tsx
- app/screens/people-screen/circles/circles-dashboard-screen.tsx
- app/screens/people-screen/circles/use-circles-card.tsx
- app/screens/people-screen/tab-icon.tsx
> chore: more circley stuff

- app/components/circle/circle.tsx
- app/components/introducing-circles-modal/introducing-circles-modal.tsx
- app/components/september-challenge/modal.tsx
- app/screens/people-screen/circles/circles-card-people-home.tsx
- app/screens/people-screen/circles/circles-dashboard-screen.tsx
- app/screens/people-screen/circles/use-circles-card.tsx
> refactor: circles pass 5

- __tests__/payment-request/helpers.ts
- __tests__/payment-request/payment-request-creation-data.spec.ts
- __tests__/payment-request/payment-request.spec.ts
- app/components/atomic/galoy-secondary-button/galoy-secondary-button.tsx
- app/components/button-group/button-group.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/i18n/raw-i18n/translations/es.json
- app/screens/receive-bitcoin-screen/payment/index.types.ts
- app/screens/receive-bitcoin-screen/payment/payment-request-creation-data.ts
- app/screens/receive-bitcoin-screen/payment/payment-request.ts
- app/screens/receive-bitcoin-screen/receive-screen.tsx
- app/screens/receive-bitcoin-screen/use-receive-bitcoin.ts
- app/screens/settings-screen/account-id.tsx
- app/screens/settings-screen/account-screen.tsx
Fixes Spanish Receive screen
Fixes https://github.com/GaloyMoney/galoy-mobile/issues/2616
> refactor: receive screen

- app/screens/people-screen/circles/circles-card-people-home.tsx
- app/screens/people-screen/circles/use-circles-card.tsx
> chore: fix circles screenshot

- android/fastlane/Fastfile
Need this for release to all at huawei
> ci: fastlane config for huawei release

- app/screens/people-screen/circles/circles-card-people-home.tsx
<table>
<thead><tr>
<td>Earlier: Fetching</td>
<td>Without Fetching</td>
<td>Now: Fetching (this PR)</td>
</tr></thead>
<tbody><tr>
<td><image src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/09a377b9-a6bc-45a1-aa61-37c63dabeac5" /></td>
<td><img src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/8b23d3d4-9885-49e2-aaf7-a077460880cb" /></td>
<td><img src="https://github.com/GaloyMoney/galoy-mobile/assets/40622610/a7adc4aa-a580-463d-8665-b6b69e8b5590" /></td>
</tr></tbody>
</table>
> chore: don't change height when refreshing circles

- app/components/circle/circle.tsx
- app/components/september-challenge/card.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/people-screen/circles/circles-dashboard-screen.tsx
- app/screens/receive-bitcoin-screen/receive-screen.tsx
- app/screens/receive-bitcoin-screen/use-receive-bitcoin.ts
- Fix BTC Address display
- Fix Background Colour for Circles Dashboard
- Easeout Circle animation to 50% for shorter values
> fix: some ui issues

- package.json
Not sure why check-code is failing.
Graphql Inspector Validation is doing something weird with browserslist and it errors at the end. I tried debugging this for many hours now and it's better to build it now.
> fix: temporary fix for graphql check

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/navigation/root-navigator.tsx
- app/navigation/stack-param-lists.ts
- app/screens/settings-screen/account-screen.tsx
- app/screens/settings-screen/notifications-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- codegen.yml
- supergraph.graphql
- add screen to set notification settings
- unify icons in settings to all be outlines
> feat: add notification settings screen

- app/components/invite-modal/invite-modal.tsx
- app/components/totp-export/totp-copy.tsx
- app/graphql/network-error-component.tsx
- app/screens/conversion-flow/conversion-confirmation-screen.tsx
- app/screens/earns-screen/earns-quiz.tsx
- app/screens/galoy-address-screen/address-component.tsx
- app/screens/map-screen/map-screen.tsx
- app/screens/people-screen/contacts/all-contacts.tsx
- app/screens/people-screen/contacts/contact-transactions.tsx
- app/screens/people-screen/contacts/contacts-card.tsx
- app/screens/receive-bitcoin-screen/use-receive-bitcoin.ts
- app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/screens/settings-screen/account-id.tsx
- app/screens/settings-screen/security-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/screens/transaction-history/transaction-history-screen.tsx
- app/utils/toast.ts
- ios/Podfile.lock
making LL a mandatory argument other "Success" would not be translated
> fix: translation for toast

- app/screens/webview/webview.tsx
it will not have a white background when darkmode is on
> chore: making the background of the webview transparent

- app/components/contact-modal/contact-modal.tsx
- app/components/contact-support-button/contact-support-button.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/error-screen/error-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/screens/settings-screen/transaction-limits-screen.tsx
also remove some code chenanigan
> chore: adding the FAQ link to the mobile app

- app/components/payment-destination-display/payment-destination-display.tsx
- app/components/wallet-summary/wallet-summary.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- app/screens/transaction-detail-screen/transaction-detail-screen.tsx
- add destination on details screen
- unify field design on confirmation screen
> chore: cleanup send flow ui

- app/components/modal-nfc/modal-nfc.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/receive-bitcoin-screen/receive-screen.tsx
- app/screens/receive-bitcoin-screen/use-receive-bitcoin.ts
Uses same LN invoice as shown on receive screen along with handling <1 sat error ahead of time.
> fix: use same invoice for NFC

- __tests__/payment-request/payment-request-creation-data.spec.ts
- __tests__/payment-request/payment-request.spec.ts
- app/screens/receive-bitcoin-screen/payment/payment-request-creation-data.ts
- app/screens/receive-bitcoin-screen/payment/payment-request.ts
fixes https://github.com/GaloyMoney/galoy-mobile/issues/2620
Related: https://github.com/GaloyMoney/galoy-pay/pull/548
> feat: allow memo in paycode

- __tests__/payment-request/payment-request-creation-data.spec.ts
- __tests__/payment-request/payment-request.spec.ts
- app/screens/receive-bitcoin-screen/payment/payment-request-creation-data.ts
- app/screens/receive-bitcoin-screen/payment/payment-request.ts
Reverts GaloyMoney/galoy-mobile#2667
> revert: "feat: allow memo in paycode"

- app/screens/settings-screen/account-screen.tsx
> fix: delete account in non english

- android/app/src/main/AndroidManifest.xml
- app/screens/settings-screen/settings-screen.tsx
- package.json
- yarn.lock
> fix: adding .csv extension when exporting txs

- android/app/src/main/AndroidManifest.xml
- app/assets/icons/nfc.svg
- app/components/custom-icon/custom-icon.tsx
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/receive-bitcoin-screen/receive-screen.tsx
> refactor: receive screen ux with NFC

- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
> fix: cache for contact when entering the send flow

- app/screens/full-onboarding-flow/full-onboarding-flow.tsx
> fix: missing pending wheel on account upgrade screen

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- bundles barcode scanning with the app to remove dependency on google play services
> fix: scanner on degoogled android

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/home-screen/home-screen.tsx
Fixes issue #2778 @nicolasburtey
> refactor: changed homescreen transactions text

- android/app/src/main/res/values-night/colors.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/styles.xml
- fixes the flash of white when keyboard appears on dark mode android
> fix: use system dark mode in android

- app/components/code-input/code-input.tsx
(maybe it's fixing it, can't reproduce anymore for some reasons)
fix #2807
> fix: pasting code for email issue

- ios/GaloyApp.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- yarn.lock
- attempt to fix black camera on android by rolling back to a previously known good react-native-vision-camera
> chore: fix camera on android

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/navigation/root-navigator.tsx
- app/screens/receive-bitcoin-screen/receive-screen.tsx
- app/screens/transaction-detail-screen/transaction-detail-screen.tsx
1. "Scan NFC" -> "NFC"
2. Pending transaction refresh: https://github.com/GaloyMoney/galoy-mobile/issues/2792
https://github.com/GaloyMoney/galoy-mobile/assets/40622610/d857f82f-c079-4fd7-acbe-ae5b03d6278c
> chore: ui issues

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/map-screen/map-screen.tsx
- app/screens/map-screen/map-styles.json
This is how it looks:
Map Style from: https://mapstyle.withgoogle.com
fixes https://github.com/GaloyMoney/galoy-mobile/issues/2819
> feat: maps android darkmode, fix the cta pay to business button

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/navigation/stack-param-lists.ts
- app/screens/send-bitcoin-screen/payment-details/index.types.ts
- app/screens/send-bitcoin-screen/payment-details/onchain.ts
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-success-screen.tsx
- app/screens/send-bitcoin-screen/use-send-payment.ts
- ios/Podfile.lock
> feat: onchain eta in success screen

- __tests__/timer.spec.ts
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/transaction-detail-screen/format-time.ts
- app/screens/transaction-detail-screen/transaction-detail-screen.tsx
note: the screen doesn't auto refresh after the tx got send to the mempool, but I'll dive into this tomorrow with a follow up PR. I dont want delay the release for this detail.
> chore: improving onchain queue display timer

- android/app/src/main/AndroidManifest.xml
- app/config/appinfo.ts
- ios/GaloyApp/GaloyApp.entitlements
- ios/GaloyApp/GaloyAppDebug.entitlements
- ios/GaloyApp/Info.plist
I don't think this is a Galoy Pay URL anymore
> chore: rm ln.bitcoinbeach.com

- app/components/atomic/galoy-currency-bubble/galoy-currency-bubble.tsx
- app/components/circle/circle.tsx
- app/components/currency-tag/currency-tag.tsx
- app/components/galoy-toast/galoy-toast.tsx
- app/components/menu-select/item.tsx
- app/components/price-history/price-history.tsx
- app/components/transaction-item/transaction-item.tsx
- app/rne-theme/colors.ts
- app/rne-theme/themed.d.ts
- app/screens/earns-screen/earns-quiz.tsx
- app/screens/receive-bitcoin-screen/receive-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-confirmation-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
- app/screens/settings-screen/transaction-limits-screen.tsx
- ios/Podfile.lock
> chore: improve toast design

- __tests__/hooks/use-show-warning-secure-account.spec.tsx
- app/screens/settings-screen/show-warning-secure-account.tsx
- package.json
- yarn.lock
note: this seems to be help, at least in my local machine, but not yet fully fixing this non deterministic build failure on github action
> fix: test timing out with nodejs 20

- .storybook/storybook.tsx
- ios/Podfile.lock
- metro.config.js
- package.json
This https://github.com/storybookjs/react-native/issues/152#issuecomment-1736493692 fixes it.
This is an issue in storybook react native which is not yet fixed, this is a workaround.
> fix: storybook

- .circleci/config.yml
We were always getting import errors for android part of the e2e tests. This should fix that.
> test(e2e): fix android import issue

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/transaction-detail-screen/transaction-detail-screen.tsx
> fix: improve text for sending onchain

- app/i18n/hu/index.ts
- app/i18n/i18n-types.ts
- app/i18n/i18n-util.async.ts
- app/i18n/i18n-util.sync.ts
- app/i18n/i18n-util.ts
- app/i18n/mapping.ts
- app/i18n/raw-i18n/translations/hu.json
Adding the translated strings in Hungarian.
The quiz is not complete yet, but started the first chapters.
> feat: add hungarian translation

- app/i18n/raw-i18n/translations/hu.json
clarifies some terms and fixes typos based on the feedback on the last 2.2.213 build
> chore: improve hungarian translation

- app/components/totp-export/totp-qr.tsx
fixes https://github.com/GaloyMoney/galoy-mobile/issues/2972
> chore: space around totp

- app/screens/receive-bitcoin-screen/receive-screen.tsx
- fixes flickering nfc button on receive screen
> fix: flickering nfc button

- app/components/transaction-item/transaction-item.tsx
- app/screens/home-screen/home-screen.tsx
- app/screens/people-screen/contacts/contact-transactions.tsx
- app/screens/transaction-history/transaction-history-screen.tsx
Fixes an issue with tx history screen being unresponsive due to the resource constraints of rendering so many TransactionItems
> fix: tx history unresponsiveness

- app/screens/send-bitcoin-screen/confirm-fees-modal.tsx
> fix: make primary action cancel for high fees tx

- app/components/push-notification/push-notification.tsx
- app/screens/receive-bitcoin-screen/receive-screen.tsx
- prevent throwing errors for incorrectly passed links
- upload device token on approval of notification permissions
> fix: notifications handling

- app/components/map-component/index.tsx
- app/components/map-marker-component/index.tsx
> feat: callout titles can wrap and are limited to two lines

- app/navigation/stack-param-lists.ts
- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
> chore: fix crash on send flow

- app/components/map-component/index.tsx
- app/components/map-component/location-button-copy.tsx
- app/components/map-marker-component/index.tsx
> fix: text on map in dark mode

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/earns-map-screen/earns-map-screen.tsx
it seems with the prior message it was not very clear that only section was available per day
> chore: improving messaging on next available session

- app/screens/send-bitcoin-screen/send-bitcoin-destination-screen.tsx
the current search capability in the send destination flow is confusing
if a user type a bitcoin address, lightning address, lnurl or an external user, we should not show the message "No Contact matching your search were found"
before
after
> fix: do not show that "contact is not found" when not relevant

- app/graphql/generated.ts
- ios/Podfile.lock
- package.json
- supergraph.graphql
- yarn.lock
probable fix #3113
in release note: https://github.com/mrousavy/react-native-vision-camera/releases/tag/v3.9.0
`👉 A fully rewritten CameraCaptureSession to fix various blackscreen issues on Android 🚀`
> chore: updating react native vision library to 3.9.1

- app/app.tsx
- app/components/contact-modal/contact-modal.tsx
so that useNavigation doesn't create a crash
> chore: putting ErrorBoundary within NavigationContainer

- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/settings-screen/settings-screen.tsx
- app/screens/settings-screen/settings/account-static-qr.tsx
- app/screens/settings-screen/settings/sp-security.tsx
> chore: addressing feedback for settings screen update

- .github/workflows/e2e.yml
- app/screens/email-registration-screen/email-registration-validate.tsx
- app/screens/settings-screen/account/account-screen.tsx
- app/screens/settings-screen/settings-screen.tsx
- app/screens/settings-screen/settings/account-pos.tsx
- app/screens/settings-screen/settings/account-static-qr.tsx
- e2e/detox/01-auth.test.ts
- e2e/detox/utils/common-flows.ts
> chore: restructuring data around settings screen

- app/components/may-challenge/card.tsx
- app/components/may-challenge/index.tsx
- app/components/may-challenge/modal.tsx
- app/graphql/generated.ts
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/people-screen/circles/circles-dashboard-screen.tsx
- app/utils/date.ts
Closes https://github.com/GaloyMoney/galoy-mobile/issues/3176
> feat: may challenge

- .github/workflows/e2e.yml
- app/graphql/generated.ts
- e2e/detox/01-auth.test.ts
- e2e/detox/02-conversion.test.ts
> test(e2e): accept tac

- app/graphql/generated.gql
- app/graphql/generated.ts
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/navigation/root-navigator.tsx
- app/navigation/stack-param-lists.ts
- app/screens/notification-history-screen/notification-history-screen.tsx
- app/screens/notification-history-screen/notification.tsx
- app/screens/notification-history-screen/utils.ts
- app/screens/settings-screen/row.tsx
- app/screens/settings-screen/settings-screen.tsx
> feat: notifications history

- app/screens/home-screen/home-screen.tsx
- app/screens/notification-history-screen/notification.tsx
Reverts GaloyMoney/blink-mobile#3241
> revert: transaction list home screen adaptive to screen size

- app/screens/settings-screen/row.tsx
- app/screens/settings-screen/settings/account-pos.tsx
- app/screens/settings-screen/settings/account-static-qr.tsx
- app/screens/settings-screen/settings/account-tx-limits.tsx
| Previous | New |
| --- | --- |
|  <img width="400" src="https://github.com/GaloyMoney/blink-mobile/assets/40622610/fde4cc30-5c20-4c8c-84a0-9135cccafa13" /> | <img width="400" src="https://github.com/GaloyMoney/blink-mobile/assets/40622610/fcbdfcd2-863f-4dcd-9990-0ed9b3ff3b69" /> |
> chore: smaller settings rows

- app/screens/settings-screen/settings/account-pos.tsx
- app/screens/settings-screen/settings/account-static-qr.tsx
> fix: pos urls

- app/components/note-input/note-input.tsx
Fixes #3290 
[Screencast from 12-06-24 08:17:41 PM IST.webm](https://github.com/GaloyMoney/blink-mobile/assets/17739006/f8650122-8e9b-47a8-9f74-8380ef302c1c)
> fix: note icon registers clicks

- app/i18n/raw-i18n/source/en.json
Seven changes to the earn section
> chore(earn): transifex issue fixes - earn section changes

- app/assets/icons/switch.svg
- app/graphql/client.tsx
- app/graphql/generated.gql
- app/graphql/generated.ts
- app/i18n/en/index.ts
- app/i18n/i18n-types.ts
- app/i18n/raw-i18n/source/en.json
- app/screens/settings-screen/account/banner.tsx
- app/screens/settings-screen/account/profile.tsx
Switch Account functionality #3273 
Adds functionality to the Profile Screen UI created in #3307
> feat: add switch account functionality

- ci/tasks/build.sh
Reverts GaloyMoney/blink-mobile#3365
> revert: "ci: build ios before android"

- android/Gemfile.lock
Reverts GaloyMoney/blink-mobile#3377
> revert: "chore: update android gemfile lock"

- app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx
fix this https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/vBFisqbvdyC?vs=hideCompare
> fix: onchain fee alert early return

- app/screens/phone-auth-screen/phone-login-input.tsx
Completes the configuration changes in: https://github.com/blinkbitcoin/blink-deployments/pull/8056
> chore: remove US from DisableCountriesForAccountCreation

- ios/GaloyApp/GaloyApp.entitlements
- ios/GaloyApp/GaloyAppDebug.entitlements
fix upload issue caused by an unsupported value in the new sdks https://developer.apple.com/documentation/bundleresources/entitlements/com.apple.developer.nfc.readersession.formats
> fix: remove ndef
